import type { IndustryId } from "./types.ts";
import { normalizeText } from "./normalize.ts";

/** English-label alphabetical order (Other is appended in the select). */
const INDUSTRY_IDS: IndustryId[] = [
  "advertising-marketing",
  "agriculture",
  "architecture",
  "artificial-intelligence",
  "automotive",
  "aviation",
  "beauty-wellness",
  "biotech",
  "clean-energy",
  "climate-tech",
  "construction",
  "consulting",
  "consumer-products",
  "creative-services",
  "culture-arts",
  "cybersecurity",
  "e-commerce",
  "education",
  "entertainment",
  "fashion",
  "finance",
  "fitness-sports",
  "food-beverage",
  "gaming",
  "government",
  "healthcare",
  "home-living",
  "hospitality",
  "insurance",
  "interior-design",
  "jewelry-luxury",
  "legal",
  "logistics",
  "manufacturing",
  "media",
  "music",
  "nonprofit",
  "pets",
  "pharmaceuticals",
  "professional-services",
  "public-relations",
  "publishing",
  "real-estate",
  "retail",
  "software",
  "technology",
  "telecommunications",
  "travel",
  "venture-capital",
];

const ALIAS_TO_ID: Record<string, IndustryId> = {
  "advertising marketing": "advertising-marketing",
  "advertising-marketing": "advertising-marketing",
  "advertising & marketing": "advertising-marketing",
  advertising: "advertising-marketing",
  marketing: "advertising-marketing",
  реклама: "advertising-marketing",
  маркетинг: "advertising-marketing",
  agriculture: "agriculture",
  агро: "agriculture",
  сельское: "agriculture",
  architecture: "architecture",
  архитектура: "architecture",
  "artificial intelligence": "artificial-intelligence",
  "artificial-intelligence": "artificial-intelligence",
  ai: "artificial-intelligence",
  "искусственный интеллект": "artificial-intelligence",
  automotive: "automotive",
  авто: "automotive",
  aviation: "aviation",
  aerospace: "aviation",
  авиация: "aviation",
  "beauty wellness": "beauty-wellness",
  "beauty-wellness": "beauty-wellness",
  "beauty & wellness": "beauty-wellness",
  красота: "beauty-wellness",
  biotech: "biotech",
  biotechnology: "biotech",
  биотех: "biotech",
  "clean energy": "clean-energy",
  "clean-energy": "clean-energy",
  "чистая энергия": "clean-energy",
  "climate tech": "climate-tech",
  "climate-tech": "climate-tech",
  climtech: "climate-tech",
  климат: "climate-tech",
  construction: "construction",
  строительство: "construction",
  consulting: "consulting",
  consultancy: "consulting",
  консалтинг: "consulting",
  "consumer products": "consumer-products",
  "consumer-products": "consumer-products",
  "потребительские товары": "consumer-products",
  "creative services": "creative-services",
  "creative-services": "creative-services",
  "креативные услуги": "creative-services",
  "culture arts": "culture-arts",
  "culture-arts": "culture-arts",
  "culture & arts": "culture-arts",
  культура: "culture-arts",
  cybersecurity: "cybersecurity",
  "cyber security": "cybersecurity",
  security: "cybersecurity",
  кибербезопасность: "cybersecurity",
  "e commerce": "e-commerce",
  "e-commerce": "e-commerce",
  ecommerce: "e-commerce",
  "электронная коммерция": "e-commerce",
  education: "education",
  образование: "education",
  entertainment: "entertainment",
  развлечения: "entertainment",
  fashion: "fashion",
  мода: "fashion",
  finance: "finance",
  финансы: "finance",
  fintech: "finance",
  "fitness sports": "fitness-sports",
  "fitness-sports": "fitness-sports",
  "fitness & sports": "fitness-sports",
  sports: "fitness-sports",
  фитнес: "fitness-sports",
  спорт: "fitness-sports",
  "food beverage": "food-beverage",
  "food-beverage": "food-beverage",
  "food & beverage": "food-beverage",
  "еда и напитки": "food-beverage",
  gaming: "gaming",
  games: "gaming",
  игры: "gaming",
  government: "government",
  "public sector": "government",
  государство: "government",
  healthcare: "healthcare",
  здравоохранение: "healthcare",
  "home living": "home-living",
  "home-living": "home-living",
  "home & living": "home-living",
  furniture: "home-living",
  дом: "home-living",
  hospitality: "hospitality",
  гостеприимство: "hospitality",
  insurance: "insurance",
  страхование: "insurance",
  "interior design": "interior-design",
  "interior-design": "interior-design",
  интерьер: "interior-design",
  "дизайн интерьера": "interior-design",
  "jewelry luxury": "jewelry-luxury",
  "jewelry-luxury": "jewelry-luxury",
  "jewelry & luxury": "jewelry-luxury",
  jewellery: "jewelry-luxury",
  luxury: "jewelry-luxury",
  ювелир: "jewelry-luxury",
  legal: "legal",
  law: "legal",
  юриспруденция: "legal",
  право: "legal",
  logistics: "logistics",
  "supply chain": "logistics",
  логистика: "logistics",
  manufacturing: "manufacturing",
  производство: "manufacturing",
  media: "media",
  медиа: "media",
  music: "music",
  музыка: "music",
  nonprofit: "nonprofit",
  "non profit": "nonprofit",
  "некоммерческие": "nonprofit",
  pets: "pets",
  pet: "pets",
  животные: "pets",
  pharmaceuticals: "pharmaceuticals",
  pharma: "pharmaceuticals",
  фарма: "pharmaceuticals",
  "professional services": "professional-services",
  "professional-services": "professional-services",
  "профессиональные услуги": "professional-services",
  "public relations": "public-relations",
  "public-relations": "public-relations",
  pr: "public-relations",
  пиар: "public-relations",
  publishing: "publishing",
  издательство: "publishing",
  "real estate": "real-estate",
  "real-estate": "real-estate",
  недвижимость: "real-estate",
  retail: "retail",
  ритейл: "retail",
  software: "software",
  saas: "software",
  софт: "software",
  technology: "technology",
  технологии: "technology",
  tech: "technology",
  telecommunications: "telecommunications",
  telecom: "telecommunications",
  телеком: "telecommunications",
  travel: "travel",
  путешествия: "travel",
  "venture capital": "venture-capital",
  "venture-capital": "venture-capital",
  vc: "venture-capital",
  "private equity": "venture-capital",
  венчур: "venture-capital",
};

export function isIndustryId(value: string): value is IndustryId {
  return (INDUSTRY_IDS as string[]).includes(value);
}

export function resolveIndustryId(value: string): IndustryId | null {
  const trimmed = value.trim();
  if (!trimmed || trimmed === "Other" || trimmed === "other") return null;
  if (isIndustryId(trimmed)) return trimmed;
  const key = normalizeText(trimmed);
  return ALIAS_TO_ID[key] ?? null;
}

export { INDUSTRY_IDS };
