import type { IndustryId } from "./types.ts";
import { normalizeText } from "./normalize.ts";

const INDUSTRY_IDS: IndustryId[] = [
  "architecture",
  "interior-design",
  "real-estate",
  "construction",
  "technology",
  "artificial-intelligence",
  "software",
  "finance",
  "healthcare",
  "beauty-wellness",
  "fashion",
  "food-beverage",
  "hospitality",
  "travel",
  "retail",
  "e-commerce",
  "education",
  "media",
  "entertainment",
  "culture-arts",
  "creative-services",
  "professional-services",
  "clean-energy",
  "automotive",
  "consumer-products",
  "nonprofit",
];

const ALIAS_TO_ID: Record<string, IndustryId> = {
  architecture: "architecture",
  архитектура: "architecture",
  "interior design": "interior-design",
  "interior-design": "interior-design",
  интерьер: "interior-design",
  "дизайн интерьера": "interior-design",
  "real estate": "real-estate",
  "real-estate": "real-estate",
  недвижимость: "real-estate",
  construction: "construction",
  строительство: "construction",
  technology: "technology",
  технологии: "technology",
  tech: "technology",
  "artificial intelligence": "artificial-intelligence",
  "artificial-intelligence": "artificial-intelligence",
  ai: "artificial-intelligence",
  "искусственный интеллект": "artificial-intelligence",
  software: "software",
  софт: "software",
  finance: "finance",
  финансы: "finance",
  fintech: "finance",
  healthcare: "healthcare",
  здравоохранение: "healthcare",
  "beauty wellness": "beauty-wellness",
  "beauty-wellness": "beauty-wellness",
  "beauty & wellness": "beauty-wellness",
  красота: "beauty-wellness",
  fashion: "fashion",
  мода: "fashion",
  "food beverage": "food-beverage",
  "food-beverage": "food-beverage",
  "food & beverage": "food-beverage",
  "еда и напитки": "food-beverage",
  hospitality: "hospitality",
  гостеприимство: "hospitality",
  travel: "travel",
  путешествия: "travel",
  retail: "retail",
  ритейл: "retail",
  "e commerce": "e-commerce",
  "e-commerce": "e-commerce",
  ecommerce: "e-commerce",
  "электронная коммерция": "e-commerce",
  education: "education",
  образование: "education",
  media: "media",
  медиа: "media",
  entertainment: "entertainment",
  развлечения: "entertainment",
  "culture arts": "culture-arts",
  "culture-arts": "culture-arts",
  "culture & arts": "culture-arts",
  культура: "culture-arts",
  "creative services": "creative-services",
  "creative-services": "creative-services",
  "креативные услуги": "creative-services",
  "professional services": "professional-services",
  "professional-services": "professional-services",
  "профессиональные услуги": "professional-services",
  "clean energy": "clean-energy",
  "clean-energy": "clean-energy",
  "чистая энергия": "clean-energy",
  automotive: "automotive",
  авто: "automotive",
  "consumer products": "consumer-products",
  "consumer-products": "consumer-products",
  "потребительские товары": "consumer-products",
  nonprofit: "nonprofit",
  "non profit": "nonprofit",
  "некоммерческие": "nonprofit",
};

export function isIndustryId(value: string): value is IndustryId {
  return (INDUSTRY_IDS as string[]).includes(value);
}

export function resolveIndustryId(value: string): IndustryId | null {
  const trimmed = value.trim();
  if (!trimmed || trimmed === "Other" || trimmed === "other") return null;
  if (isIndustryId(trimmed)) return trimmed;
  const key = normalizeText(trimmed);
  return ALIAS_TO_ID[key] ?? null;
}

export { INDUSTRY_IDS };
