import type { IndustryId, SuggestionPool } from "./types.ts";

const BRAND_REFS = {
  pentagram: {
    name: "Pentagram",
    website: "https://www.pentagram.com",
    country: "USA",
    tags: ["identity", "systems"],
    category: "visual-identity" as const,
    bucket: "visual-identity" as const,
  },
  dumbar: {
    name: "Studio Dumbar",
    website: "https://studiodumbar.com",
    country: "Netherlands",
    tags: ["motion", "identity"],
    category: "motion" as const,
    bucket: "motion" as const,
  },
  collins: {
    name: "Collins",
    website: "https://www.wearecollins.com",
    country: "USA",
    tags: ["identity", "tone"],
    category: "tone-of-voice" as const,
    bucket: "tone-of-voice" as const,
  },
  base: {
    name: "Base Design",
    website: "https://basedesign.com",
    country: "Belgium",
    tags: ["digital", "identity"],
    category: "digital" as const,
    bucket: "digital" as const,
  },
  manual: {
    name: "Manual",
    website: "https://manualcreative.com",
    country: "USA",
    tags: ["typography", "identity"],
    category: "typography" as const,
    bucket: "typography" as const,
  },
  mucho: {
    name: "Mucho",
    website: "https://wearemucho.com",
    country: "Spain",
    tags: ["identity", "color"],
    category: "color" as const,
    bucket: "visual-identity" as const,
  },
  ordinary: {
    name: "Ordinary",
    website: "https://ordinary.co",
    country: "USA",
    tags: ["typography", "editorial"],
    category: "typography" as const,
    bucket: "typography" as const,
  },
  build: {
    name: "Build",
    website: "https://wearebuild.com",
    country: "UK",
    tags: ["typography", "identity"],
    category: "typography" as const,
    bucket: "typography" as const,
  },
  jetset: {
    name: "Experimental Jetset",
    website: "https://www.experimentaljetset.nl",
    country: "Netherlands",
    tags: ["editorial", "typography"],
    category: "editorial" as const,
    bucket: "typography" as const,
  },
  sagmeisterWalsh: {
    name: "Sagmeister & Walsh",
    website: "https://sagmeisterwalsh.com",
    country: "USA",
    tags: ["identity", "expression"],
    category: "visual-identity" as const,
    bucket: "visual-identity" as const,
  },
};

export const DEFAULT_REFERENCES = [
  BRAND_REFS.pentagram,
  BRAND_REFS.dumbar,
  BRAND_REFS.collins,
  BRAND_REFS.base,
  BRAND_REFS.manual,
  BRAND_REFS.mucho,
];

export const INDUSTRY_SUGGESTIONS: Record<IndustryId, SuggestionPool> = {
  architecture: {
    direct: [
      {
        name: "OMA",
        website: "https://www.oma.com",
        country: "Netherlands",
        tags: ["global", "cultural"],
        bucket: "scale",
        reason: {
          en: "International practice of comparable scale and cultural influence",
          ru: "Международное бюро сопоставимого масштаба и культурного влияния",
        },
      },
      {
        name: "Snøhetta",
        website: "https://snohetta.com",
        country: "Norway",
        tags: ["global", "public"],
        bucket: "scale",
      },
      {
        name: "BIG",
        website: "https://big.dk",
        country: "Denmark",
        tags: ["global", "bold"],
        bucket: "scale",
      },
      {
        name: "Foster + Partners",
        website: "https://www.fosterandpartners.com",
        country: "UK",
        tags: ["global", "corporate"],
        bucket: "scale",
      },
      {
        name: "MVRDV",
        website: "https://www.mvrdv.com",
        country: "Netherlands",
        tags: ["experimental", "urban"],
        bucket: "adjacent",
      },
      {
        name: "Norm Architects",
        website: "https://normcph.com",
        country: "Denmark",
        tags: ["minimal", "residential", "premium"],
        bucket: "close",
        reason: {
          en: "Similar minimal approach and premium residential segment",
          ru: "Минималистичный подход и премиальный residential-сегмент",
        },
      },
      {
        name: "UNStudio",
        website: "https://www.unstudio.com",
        country: "Netherlands",
        tags: ["global", "digital"],
        bucket: "adjacent",
      },
      {
        name: "MAD Architects",
        website: "https://www.i-mad.com",
        country: "China",
        tags: ["experimental", "cultural"],
        bucket: "adjacent",
      },
      {
        name: "David Chipperfield",
        website: "https://davidchipperfield.com",
        country: "UK",
        tags: ["minimal", "cultural"],
        bucket: "close",
      },
      {
        name: "Aires Mateus",
        website: "https://www.airesmateus.com",
        country: "Portugal",
        tags: ["minimal", "independent"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.jetset,
      BRAND_REFS.ordinary,
      BRAND_REFS.build,
      BRAND_REFS.manual,
    ],
    keywords: [
      {
        match:
          /hospitality|hotel|restaurant|interior|гостиниц|отел|ресторан|интерьер/i,
        weight: 20,
        bucket: "close",
        tags: ["hospitality", "interior"],
        direct: [
          "Neri&Hu",
          "Space Copenhagen",
          "Yabu Pushelberg",
          "Studio Mumbai",
        ],
      },
      {
        match:
          /minimal|private|house|residential|quiet|жилой|частн|минимал|дом/i,
        weight: 20,
        bucket: "close",
        tags: ["residential", "minimal"],
        direct: [
          "Norm Architects",
          "John Pawson",
          "Aires Mateus",
          "David Chipperfield",
        ],
      },
      {
        match: /cultural|museum|biennale|культур|музей|галере/i,
        weight: 18,
        bucket: "adjacent",
        tags: ["cultural"],
        direct: ["MAD Architects", "OMA", "Snøhetta", "Assemble"],
      },
      {
        match: /experimental|bold|радикал|эксперимент/i,
        weight: 18,
        bucket: "adjacent",
        tags: ["experimental"],
        direct: ["MAD Architects", "MVRDV", "UNStudio", "Assemble"],
      },
      {
        match:
          /sustainable|circular|timber|ecological|устойчив|эколог|дерев/i,
        weight: 20,
        bucket: "close",
        tags: ["sustainable", "timber"],
        direct: [
          "Henning Larsen",
          "White Arkitekter",
          "Lendager",
          "Waugh Thistleton Architects",
        ],
      },
      {
        match: /landscape|ландшафт|garden|сад/i,
        weight: 18,
        bucket: "adjacent",
        tags: ["landscape"],
        direct: ["Gustafson Porter", "West 8", "Michel Desvigne"],
      },
      {
        match: /urban|мастер.?план|урбан|city.?plan/i,
        weight: 18,
        bucket: "adjacent",
        tags: ["urbanism"],
        direct: ["MVRDV", "OMA", "Gehl", "UNStudio"],
      },
      {
        match: /public.?space|общественн|площад/i,
        weight: 16,
        bucket: "regional",
        tags: ["public"],
        direct: ["Snøhetta", "Gehl", "Assemble"],
      },
      {
        match: /restor|реставрац|heritage|памятник/i,
        weight: 16,
        bucket: "close",
        tags: ["restoration"],
        direct: ["David Chipperfield", "Caruso St John", "Jørn Utzon"],
      },
      {
        match: /reconstr|реконструк/i,
        weight: 16,
        bucket: "close",
        tags: ["reconstruction"],
        direct: ["OMA", "David Chipperfield", "Caruso St John"],
      },
      {
        match: /international|global|large|corporate|международ|глобал|крупн/i,
        weight: 15,
        bucket: "scale",
        tags: ["global"],
        direct: ["OMA", "BIG", "Snøhetta", "Foster + Partners"],
      },
      {
        match:
          /independent|boutique|local|studio|независим|локальн|небольш/i,
        exclude: /international|global|корпорат/i,
        weight: 15,
        bucket: "regional",
        tags: ["independent"],
        direct: [
          "Norm Architects",
          "Aires Mateus",
          "John Pawson",
          "Studio Mumbai",
        ],
      },
    ],
  },

  "interior-design": {
    direct: [
      {
        name: "Neri&Hu",
        website: "https://www.neriandhu.com",
        country: "China",
        tags: ["hospitality", "premium"],
        bucket: "close",
      },
      {
        name: "Space Copenhagen",
        website: "https://spacecph.com",
        country: "Denmark",
        tags: ["hospitality", "minimal"],
        bucket: "close",
      },
      {
        name: "Yabu Pushelberg",
        website: "https://www.yabupushelberg.com",
        country: "Canada",
        tags: ["hospitality", "global"],
        bucket: "scale",
      },
      {
        name: "Studio Mumbai",
        website: "https://www.studiomumbai.com",
        country: "India",
        tags: ["craft", "independent"],
        bucket: "regional",
      },
      {
        name: "Kelly Wearstler",
        website: "https://www.kellywearstler.com",
        country: "USA",
        tags: ["residential", "bold"],
        bucket: "adjacent",
      },
      {
        name: "Dimorestudio",
        website: "https://www.dimorestudio.eu",
        country: "Italy",
        tags: ["residential", "premium"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.ordinary,
      BRAND_REFS.build,
      BRAND_REFS.mucho,
    ],
  },

  "real-estate": {
    direct: [
      {
        name: "Related Companies",
        website: "https://www.related.com",
        country: "USA",
        tags: ["developer", "global"],
        bucket: "scale",
      },
      {
        name: "Brookfield Properties",
        website: "https://www.brookfieldproperties.com",
        country: "Canada",
        tags: ["developer", "global"],
        bucket: "scale",
      },
      {
        name: "Compass",
        website: "https://www.compass.com",
        country: "USA",
        tags: ["brokerage", "digital"],
        bucket: "close",
      },
      {
        name: "Sotheby's International Realty",
        website: "https://www.sothebysrealty.com",
        country: "USA",
        tags: ["luxury", "brokerage"],
        bucket: "close",
      },
      {
        name: "Knight Frank",
        website: "https://www.knightfrank.com",
        country: "UK",
        tags: ["advisory", "global"],
        bucket: "scale",
      },
      {
        name: "JLL",
        website: "https://www.jll.com",
        country: "USA",
        tags: ["advisory", "global"],
        bucket: "scale",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.base,
    ],
  },

  construction: {
    direct: [
      {
        name: "Turner Construction",
        website: "https://www.turnerconstruction.com",
        country: "USA",
        tags: ["global", "commercial"],
        bucket: "scale",
      },
      {
        name: "Skanska",
        website: "https://www.skanska.com",
        country: "Sweden",
        tags: ["global", "sustainable"],
        bucket: "scale",
      },
      {
        name: "AECOM",
        website: "https://aecom.com",
        country: "USA",
        tags: ["global", "infrastructure"],
        bucket: "scale",
      },
      {
        name: "Bouygues",
        website: "https://www.bouygues.com",
        country: "France",
        tags: ["global"],
        bucket: "scale",
      },
      {
        name: "Multiplex",
        website: "https://www.multiplex.global",
        country: "Australia",
        tags: ["commercial"],
        bucket: "close",
      },
      {
        name: "Lendlease",
        website: "https://www.lendlease.com",
        country: "Australia",
        tags: ["developer"],
        bucket: "adjacent",
      },
    ],
    references: [BRAND_REFS.pentagram, BRAND_REFS.dumbar, BRAND_REFS.manual],
  },

  technology: {
    direct: [
      {
        name: "Linear",
        website: "https://linear.app",
        country: "USA",
        tags: ["saas", "b2b"],
        bucket: "close",
      },
      {
        name: "Notion",
        website: "https://www.notion.com",
        country: "USA",
        tags: ["saas", "productivity"],
        bucket: "close",
      },
      {
        name: "Figma",
        website: "https://www.figma.com",
        country: "USA",
        tags: ["saas", "design"],
        bucket: "close",
      },
      {
        name: "Stripe",
        website: "https://stripe.com",
        country: "USA",
        tags: ["fintech", "infrastructure"],
        bucket: "adjacent",
      },
      {
        name: "Vercel",
        website: "https://vercel.com",
        country: "USA",
        tags: ["developer", "platform"],
        bucket: "close",
      },
      {
        name: "Arc",
        website: "https://arc.net",
        country: "USA",
        tags: ["consumer", "browser"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.base,
      BRAND_REFS.manual,
      BRAND_REFS.mucho,
    ],
    keywords: [
      {
        match:
          /\b(ai|artificial intelligence|machine learning|ml|agentic)\b|искусственн|нейросет|машинн.?обуч/i,
        weight: 20,
        bucket: "close",
        tags: ["ai"],
        direct: ["OpenAI", "Anthropic", "Perplexity", "Hugging Face"],
      },
    ],
  },

  "artificial-intelligence": {
    direct: [
      {
        name: "OpenAI",
        website: "https://openai.com",
        country: "USA",
        tags: ["foundation", "global"],
        bucket: "scale",
      },
      {
        name: "Anthropic",
        website: "https://www.anthropic.com",
        country: "USA",
        tags: ["foundation", "safety"],
        bucket: "close",
      },
      {
        name: "Perplexity",
        website: "https://www.perplexity.ai",
        country: "USA",
        tags: ["search", "consumer"],
        bucket: "close",
      },
      {
        name: "Hugging Face",
        website: "https://huggingface.co",
        country: "USA",
        tags: ["open-source", "platform"],
        bucket: "adjacent",
      },
      {
        name: "Cohere",
        website: "https://cohere.com",
        country: "Canada",
        tags: ["enterprise", "b2b"],
        bucket: "close",
      },
      {
        name: "Mistral",
        website: "https://mistral.ai",
        country: "France",
        tags: ["foundation", "european"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.base,
    ],
  },

  software: {
    direct: [
      {
        name: "Linear",
        website: "https://linear.app",
        country: "USA",
        tags: ["saas", "b2b"],
        bucket: "close",
      },
      {
        name: "Notion",
        website: "https://www.notion.com",
        country: "USA",
        tags: ["saas", "productivity"],
        bucket: "close",
      },
      {
        name: "Figma",
        website: "https://www.figma.com",
        country: "USA",
        tags: ["design", "saas"],
        bucket: "close",
      },
      {
        name: "Slack",
        website: "https://slack.com",
        country: "USA",
        tags: ["collaboration", "global"],
        bucket: "scale",
      },
      {
        name: "Asana",
        website: "https://asana.com",
        country: "USA",
        tags: ["productivity", "b2b"],
        bucket: "close",
      },
      {
        name: "Airtable",
        website: "https://www.airtable.com",
        country: "USA",
        tags: ["platform", "saas"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.base,
      BRAND_REFS.manual,
    ],
  },

  finance: {
    direct: [
      {
        name: "Stripe",
        website: "https://stripe.com",
        country: "USA",
        tags: ["payments", "b2b"],
        bucket: "close",
      },
      {
        name: "Revolut",
        website: "https://www.revolut.com",
        country: "UK",
        tags: ["neobank", "consumer"],
        bucket: "close",
      },
      {
        name: "Wise",
        website: "https://wise.com",
        country: "UK",
        tags: ["transfers", "global"],
        bucket: "close",
      },
      {
        name: "Robinhood",
        website: "https://robinhood.com",
        country: "USA",
        tags: ["brokerage", "consumer"],
        bucket: "adjacent",
      },
      {
        name: "Plaid",
        website: "https://plaid.com",
        country: "USA",
        tags: ["infrastructure", "b2b"],
        bucket: "adjacent",
      },
      {
        name: "Klarna",
        website: "https://www.klarna.com",
        country: "Sweden",
        tags: ["payments", "consumer"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.mucho,
    ],
  },

  healthcare: {
    direct: [
      {
        name: "One Medical",
        website: "https://www.onemedical.com",
        country: "USA",
        tags: ["clinic", "consumer"],
        bucket: "close",
      },
      {
        name: "Oscar Health",
        website: "https://www.hioscar.com",
        country: "USA",
        tags: ["insurance", "digital"],
        bucket: "close",
      },
      {
        name: "Ro",
        website: "https://ro.co",
        country: "USA",
        tags: ["telehealth", "dtc"],
        bucket: "close",
      },
      {
        name: "Hims",
        website: "https://www.hims.com",
        country: "USA",
        tags: ["telehealth", "dtc"],
        bucket: "adjacent",
      },
      {
        name: "Teladoc",
        website: "https://www.teladoc.com",
        country: "USA",
        tags: ["telehealth", "global"],
        bucket: "scale",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.base,
      BRAND_REFS.manual,
    ],
  },

  "beauty-wellness": {
    direct: [
      {
        name: "Aesop",
        website: "https://www.aesop.com",
        country: "Australia",
        tags: ["premium", "retail"],
        bucket: "close",
      },
      {
        name: "The Ordinary",
        website: "https://theordinary.com",
        country: "Canada",
        tags: ["accessible", "skincare"],
        bucket: "close",
      },
      {
        name: "Glossier",
        website: "https://www.glossier.com",
        country: "USA",
        tags: ["dtc", "beauty"],
        bucket: "close",
      },
      {
        name: "Le Labo",
        website: "https://www.lelabofragrances.com",
        country: "USA",
        tags: ["fragrance", "premium"],
        bucket: "adjacent",
      },
      {
        name: "Byredo",
        website: "https://www.byredo.com",
        country: "Sweden",
        tags: ["fragrance", "luxury"],
        bucket: "adjacent",
      },
      {
        name: "Rituals",
        website: "https://www.rituals.com",
        country: "Netherlands",
        tags: ["wellness", "retail"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.ordinary,
      BRAND_REFS.mucho,
    ],
  },

  fashion: {
    direct: [
      {
        name: "COS",
        website: "https://www.cos.com",
        country: "Sweden",
        tags: ["minimal", "retail"],
        bucket: "close",
      },
      {
        name: "Acne Studios",
        website: "https://www.acnestudios.com",
        country: "Sweden",
        tags: ["premium", "fashion"],
        bucket: "close",
      },
      {
        name: "Everlane",
        website: "https://www.everlane.com",
        country: "USA",
        tags: ["dtc", "accessible"],
        bucket: "close",
      },
      {
        name: "Toteme",
        website: "https://toteme.com",
        country: "Sweden",
        tags: ["minimal", "premium"],
        bucket: "close",
      },
      {
        name: "Arket",
        website: "https://www.arket.com",
        country: "Sweden",
        tags: ["lifestyle", "retail"],
        bucket: "adjacent",
      },
      {
        name: "Our Legacy",
        website: "https://www.ourlegacy.com",
        country: "Sweden",
        tags: ["independent", "premium"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.ordinary,
      BRAND_REFS.build,
    ],
  },

  "food-beverage": {
    direct: [
      {
        name: "Blue Bottle",
        website: "https://bluebottlecoffee.com",
        country: "USA",
        tags: ["coffee", "premium"],
        bucket: "close",
      },
      {
        name: "Tim Wendelboe",
        website: "https://www.timwendelboe.no",
        country: "Norway",
        tags: ["coffee", "specialty"],
        bucket: "close",
      },
      {
        name: "April Coffee",
        website: "https://aprilcoffeeroasters.com",
        country: "Denmark",
        tags: ["coffee", "specialty"],
        bucket: "close",
      },
      {
        name: "La Cabra",
        website: "https://lacabra.dk",
        country: "Denmark",
        tags: ["coffee", "specialty"],
        bucket: "regional",
      },
      {
        name: "Square Mile",
        website: "https://shop.squaremilecoffee.com",
        country: "UK",
        tags: ["coffee", "specialty"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.ordinary,
      BRAND_REFS.mucho,
    ],
    keywords: [
      {
        match: /coffee|roast|café|cafe|кофе|обжар/i,
        weight: 20,
        bucket: "close",
        tags: ["coffee"],
        direct: [
          "Blue Bottle",
          "Tim Wendelboe",
          "April Coffee",
          "La Cabra",
          "Square Mile",
        ],
      },
      {
        match: /barber|groom|hair|барбер|парикмах/i,
        weight: 18,
        bucket: "adjacent",
        tags: ["grooming"],
        direct: ["Blind Barber", "Schorem", "Fellow Barber"],
      },
    ],
  },

  hospitality: {
    direct: [
      {
        name: "Ace Hotel",
        website: "https://acehotel.com",
        country: "USA",
        tags: ["boutique", "lifestyle"],
        bucket: "close",
      },
      {
        name: "Soho House",
        website: "https://www.sohohouse.com",
        country: "UK",
        tags: ["members", "premium"],
        bucket: "close",
      },
      {
        name: "Edition",
        website: "https://www.editionhotels.com",
        country: "USA",
        tags: ["luxury", "global"],
        bucket: "scale",
      },
      {
        name: "The Standard",
        website: "https://www.standardhotels.com",
        country: "USA",
        tags: ["boutique", "urban"],
        bucket: "close",
      },
      {
        name: "Aman",
        website: "https://www.aman.com",
        country: "Singapore",
        tags: ["luxury", "global"],
        bucket: "scale",
      },
      {
        name: "Nobu Hotels",
        website: "https://www.nobuhotels.com",
        country: "USA",
        tags: ["luxury", "hospitality"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.ordinary,
      BRAND_REFS.build,
    ],
  },

  travel: {
    direct: [
      {
        name: "Airbnb",
        website: "https://www.airbnb.com",
        country: "USA",
        tags: ["platform", "global"],
        bucket: "scale",
      },
      {
        name: "Kayak",
        website: "https://www.kayak.com",
        country: "USA",
        tags: ["search", "digital"],
        bucket: "close",
      },
      {
        name: "Booking.com",
        website: "https://www.booking.com",
        country: "Netherlands",
        tags: ["platform", "global"],
        bucket: "scale",
      },
      {
        name: "Away",
        website: "https://www.awaytravel.com",
        country: "USA",
        tags: ["luggage", "dtc"],
        bucket: "adjacent",
      },
      {
        name: "Monocle",
        website: "https://monocle.com",
        country: "UK",
        tags: ["editorial", "travel"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.base,
      BRAND_REFS.manual,
    ],
  },

  retail: {
    direct: [
      {
        name: "COS",
        website: "https://www.cos.com",
        country: "Sweden",
        tags: ["fashion", "minimal"],
        bucket: "close",
      },
      {
        name: "Arket",
        website: "https://www.arket.com",
        country: "Sweden",
        tags: ["lifestyle", "retail"],
        bucket: "close",
      },
      {
        name: "Aesop",
        website: "https://www.aesop.com",
        country: "Australia",
        tags: ["beauty", "premium"],
        bucket: "adjacent",
      },
      {
        name: "Muji",
        website: "https://www.muji.com",
        country: "Japan",
        tags: ["lifestyle", "minimal"],
        bucket: "close",
      },
      {
        name: "Everlane",
        website: "https://www.everlane.com",
        country: "USA",
        tags: ["dtc", "fashion"],
        bucket: "close",
      },
      {
        name: "SSENSE",
        website: "https://www.ssense.com",
        country: "Canada",
        tags: ["luxury", "e-commerce"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.ordinary,
      BRAND_REFS.mucho,
    ],
  },

  "e-commerce": {
    direct: [
      {
        name: "Shopify",
        website: "https://www.shopify.com",
        country: "Canada",
        tags: ["platform", "b2b"],
        bucket: "close",
      },
      {
        name: "Stripe",
        website: "https://stripe.com",
        country: "USA",
        tags: ["payments", "infrastructure"],
        bucket: "adjacent",
      },
      {
        name: "Glossier",
        website: "https://www.glossier.com",
        country: "USA",
        tags: ["dtc", "beauty"],
        bucket: "close",
      },
      {
        name: "Away",
        website: "https://www.awaytravel.com",
        country: "USA",
        tags: ["dtc", "product"],
        bucket: "close",
      },
      {
        name: "Everlane",
        website: "https://www.everlane.com",
        country: "USA",
        tags: ["dtc", "fashion"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.base,
      BRAND_REFS.manual,
    ],
  },

  education: {
    direct: [
      {
        name: "Coursera",
        website: "https://www.coursera.org",
        country: "USA",
        tags: ["platform", "global"],
        bucket: "scale",
      },
      {
        name: "MasterClass",
        website: "https://www.masterclass.com",
        country: "USA",
        tags: ["premium", "video"],
        bucket: "close",
      },
      {
        name: "Khan Academy",
        website: "https://www.khanacademy.org",
        country: "USA",
        tags: ["nonprofit", "accessible"],
        bucket: "adjacent",
      },
      {
        name: "Duolingo",
        website: "https://www.duolingo.com",
        country: "USA",
        tags: ["language", "consumer"],
        bucket: "close",
      },
      {
        name: "Skillshare",
        website: "https://www.skillshare.com",
        country: "USA",
        tags: ["creative", "platform"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.base,
    ],
  },

  media: {
    direct: [
      {
        name: "Monocle",
        website: "https://monocle.com",
        country: "UK",
        tags: ["editorial", "premium"],
        bucket: "close",
      },
      {
        name: "The Atlantic",
        website: "https://www.theatlantic.com",
        country: "USA",
        tags: ["editorial", "digital"],
        bucket: "close",
      },
      {
        name: "Pitchfork",
        website: "https://pitchfork.com",
        country: "USA",
        tags: ["music", "editorial"],
        bucket: "adjacent",
      },
      {
        name: "Spotify",
        website: "https://www.spotify.com",
        country: "Sweden",
        tags: ["audio", "platform"],
        bucket: "adjacent",
      },
      {
        name: "Substack",
        website: "https://substack.com",
        country: "USA",
        tags: ["publishing", "platform"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.jetset,
      BRAND_REFS.ordinary,
    ],
  },

  entertainment: {
    direct: [
      {
        name: "Spotify",
        website: "https://www.spotify.com",
        country: "Sweden",
        tags: ["audio", "global"],
        bucket: "scale",
      },
      {
        name: "Netflix",
        website: "https://www.netflix.com",
        country: "USA",
        tags: ["streaming", "global"],
        bucket: "scale",
      },
      {
        name: "Disney",
        website: "https://www.disney.com",
        country: "USA",
        tags: ["media", "global"],
        bucket: "scale",
      },
      {
        name: "Twitch",
        website: "https://www.twitch.tv",
        country: "USA",
        tags: ["live", "community"],
        bucket: "close",
      },
      {
        name: "Patreon",
        website: "https://www.patreon.com",
        country: "USA",
        tags: ["creator", "platform"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.mucho,
    ],
  },

  "culture-arts": {
    direct: [
      {
        name: "Tate",
        website: "https://www.tate.org.uk",
        country: "UK",
        tags: ["museum", "cultural"],
        bucket: "close",
      },
      {
        name: "MoMA",
        website: "https://www.moma.org",
        country: "USA",
        tags: ["museum", "cultural"],
        bucket: "close",
      },
      {
        name: "Serpentine",
        website: "https://www.serpentinegalleries.org",
        country: "UK",
        tags: ["gallery", "contemporary"],
        bucket: "close",
      },
      {
        name: "Palais de Tokyo",
        website: "https://palaisdetokyo.com",
        country: "France",
        tags: ["gallery", "contemporary"],
        bucket: "regional",
      },
      {
        name: "Hauser & Wirth",
        website: "https://www.hauserwirth.com",
        country: "Switzerland",
        tags: ["gallery", "global"],
        bucket: "scale",
      },
      {
        name: "Art Basel",
        website: "https://www.artbasel.com",
        country: "Switzerland",
        tags: ["fair", "global"],
        bucket: "scale",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.jetset,
      BRAND_REFS.ordinary,
    ],
  },

  "creative-services": {
    direct: [
      {
        name: "Pentagram",
        website: "https://www.pentagram.com",
        country: "USA",
        tags: ["identity", "global"],
        bucket: "scale",
      },
      {
        name: "Collins",
        website: "https://www.wearecollins.com",
        country: "USA",
        tags: ["identity", "strategy"],
        bucket: "close",
      },
      {
        name: "Base Design",
        website: "https://basedesign.com",
        country: "Belgium",
        tags: ["identity", "digital"],
        bucket: "close",
      },
      {
        name: "Manual",
        website: "https://manualcreative.com",
        country: "USA",
        tags: ["identity", "typography"],
        bucket: "close",
      },
      {
        name: "Mucho",
        website: "https://wearemucho.com",
        country: "Spain",
        tags: ["identity", "independent"],
        bucket: "regional",
      },
      {
        name: "Sagmeister & Walsh",
        website: "https://sagmeisterwalsh.com",
        country: "USA",
        tags: ["identity", "expression"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.dumbar,
      BRAND_REFS.jetset,
      BRAND_REFS.ordinary,
      BRAND_REFS.build,
    ],
  },

  "professional-services": {
    direct: [
      {
        name: "McKinsey",
        website: "https://www.mckinsey.com",
        country: "USA",
        tags: ["consulting", "global"],
        bucket: "scale",
      },
      {
        name: "IDEO",
        website: "https://www.ideo.com",
        country: "USA",
        tags: ["design", "innovation"],
        bucket: "close",
      },
      {
        name: "Accenture",
        website: "https://www.accenture.com",
        country: "Ireland",
        tags: ["consulting", "global"],
        bucket: "scale",
      },
      {
        name: "Deloitte",
        website: "https://www.deloitte.com",
        country: "UK",
        tags: ["consulting", "global"],
        bucket: "scale",
      },
      {
        name: "BCG",
        website: "https://www.bcg.com",
        country: "USA",
        tags: ["consulting", "global"],
        bucket: "scale",
      },
      {
        name: "Frog",
        website: "https://www.frog.co",
        country: "USA",
        tags: ["design", "innovation"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.base,
    ],
  },

  "clean-energy": {
    direct: [
      {
        name: "Tesla Energy",
        website: "https://www.tesla.com/energy",
        country: "USA",
        tags: ["storage", "global"],
        bucket: "scale",
      },
      {
        name: "Sunrun",
        website: "https://www.sunrun.com",
        country: "USA",
        tags: ["solar", "residential"],
        bucket: "close",
      },
      {
        name: "Octopus Energy",
        website: "https://octopus.energy",
        country: "UK",
        tags: ["utility", "retail"],
        bucket: "close",
      },
      {
        name: "Enphase",
        website: "https://enphase.com",
        country: "USA",
        tags: ["hardware", "solar"],
        bucket: "close",
      },
      {
        name: "Sonnen",
        website: "https://sonnen.de",
        country: "Germany",
        tags: ["storage", "european"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.base,
      {
        name: "Nest",
        website: "https://store.google.com/category/connected_home",
        country: "USA",
        tags: ["smart-home", "product"],
        category: "digital",
        bucket: "digital",
        reason: {
          en: "Reference for product UI and calm smart-home aesthetics",
          ru: "Ориентир по продуктовому UI и спокойной smart-home эстетике",
        },
      },
    ],
  },

  automotive: {
    direct: [
      {
        name: "Tesla",
        website: "https://www.tesla.com",
        country: "USA",
        tags: ["ev", "global"],
        bucket: "scale",
      },
      {
        name: "Rivian",
        website: "https://rivian.com",
        country: "USA",
        tags: ["ev", "adventure"],
        bucket: "close",
      },
      {
        name: "Polestar",
        website: "https://www.polestar.com",
        country: "Sweden",
        tags: ["ev", "premium"],
        bucket: "close",
      },
      {
        name: "BMW",
        website: "https://www.bmw.com",
        country: "Germany",
        tags: ["premium", "global"],
        bucket: "scale",
      },
      {
        name: "Porsche",
        website: "https://www.porsche.com",
        country: "Germany",
        tags: ["luxury", "performance"],
        bucket: "adjacent",
      },
      {
        name: "Lucid",
        website: "https://www.lucidmotors.com",
        country: "USA",
        tags: ["ev", "luxury"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.dumbar,
      BRAND_REFS.manual,
    ],
  },

  "consumer-products": {
    direct: [
      {
        name: "Muji",
        website: "https://www.muji.com",
        country: "Japan",
        tags: ["minimal", "lifestyle"],
        bucket: "close",
      },
      {
        name: "Aesop",
        website: "https://www.aesop.com",
        country: "Australia",
        tags: ["premium", "retail"],
        bucket: "adjacent",
      },
      {
        name: "Dyson",
        website: "https://www.dyson.com",
        country: "UK",
        tags: ["hardware", "premium"],
        bucket: "close",
      },
      {
        name: "Bang & Olufsen",
        website: "https://www.bang-olufsen.com",
        country: "Denmark",
        tags: ["audio", "luxury"],
        bucket: "adjacent",
      },
      {
        name: "Teenage Engineering",
        website: "https://teenage.engineering",
        country: "Sweden",
        tags: ["hardware", "design"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.ordinary,
      BRAND_REFS.dumbar,
      BRAND_REFS.mucho,
    ],
  },

  nonprofit: {
    direct: [
      {
        name: "charity: water",
        website: "https://www.charitywater.org",
        country: "USA",
        tags: ["impact", "water"],
        bucket: "close",
      },
      {
        name: "Wikipedia",
        website: "https://www.wikipedia.org",
        country: "USA",
        tags: ["knowledge", "platform"],
        bucket: "adjacent",
      },
      {
        name: "Red Cross",
        website: "https://www.icrc.org",
        country: "Switzerland",
        tags: ["humanitarian", "global"],
        bucket: "scale",
      },
      {
        name: "WWF",
        website: "https://www.worldwildlife.org",
        country: "Switzerland",
        tags: ["environment", "global"],
        bucket: "scale",
      },
      {
        name: "Amnesty International",
        website: "https://www.amnesty.org",
        country: "UK",
        tags: ["rights", "global"],
        bucket: "scale",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.base,
    ],
  },
};

/** Extra company metadata for keyword-only names. */
export const COMPANY_CATALOG: Record<
  string,
  { website?: string; country?: string; tags?: string[]; reason?: string }
> = {
  "neri&hu": {
    website: "https://www.neriandhu.com",
    country: "China",
    tags: ["hospitality", "interior"],
  },
  "space copenhagen": {
    website: "https://spacecph.com",
    country: "Denmark",
    tags: ["hospitality", "interior"],
  },
  "yabu pushelberg": {
    website: "https://www.yabupushelberg.com",
    country: "Canada",
    tags: ["hospitality"],
  },
  "studio mumbai": {
    website: "https://www.studiomumbai.com",
    country: "India",
    tags: ["craft"],
  },
  "john pawson": {
    website: "https://www.johnpawson.com",
    country: "UK",
    tags: ["minimal", "residential"],
  },
  assemble: {
    website: "https://assemblestudio.co.uk",
    country: "UK",
    tags: ["cultural", "independent"],
  },
  "henning larsen": {
    website: "https://henninglarsen.com",
    country: "Denmark",
    tags: ["sustainable"],
  },
  "white arkitekter": {
    website: "https://whitearkitekter.com",
    country: "Sweden",
    tags: ["sustainable"],
  },
  lendager: {
    website: "https://lendager.com",
    country: "Denmark",
    tags: ["circular"],
  },
  "waugh thistleton architects": {
    website: "https://waughthistleton.com",
    country: "UK",
    tags: ["timber"],
  },
  openai: { website: "https://openai.com", country: "USA", tags: ["ai"] },
  anthropic: {
    website: "https://www.anthropic.com",
    country: "USA",
    tags: ["ai"],
  },
  perplexity: {
    website: "https://www.perplexity.ai",
    country: "USA",
    tags: ["ai"],
  },
  "hugging face": {
    website: "https://huggingface.co",
    country: "USA",
    tags: ["ai"],
  },
};
