import type { IndustryId, SuggestionPool } from "./types.ts";

const BRAND_REFS = {
  pentagram: {
    name: "Pentagram",
    website: "https://www.pentagram.com",
    country: "USA",
    tags: ["identity", "systems"],
    category: "visual-identity" as const,
    bucket: "visual-identity" as const,
  },
  dumbar: {
    name: "Studio Dumbar",
    website: "https://studiodumbar.com",
    country: "Netherlands",
    tags: ["motion", "identity"],
    category: "motion" as const,
    bucket: "motion" as const,
  },
  collins: {
    name: "Collins",
    website: "https://www.wearecollins.com",
    country: "USA",
    tags: ["identity", "tone"],
    category: "tone-of-voice" as const,
    bucket: "tone-of-voice" as const,
  },
  base: {
    name: "Base Design",
    website: "https://basedesign.com",
    country: "Belgium",
    tags: ["digital", "identity"],
    category: "digital" as const,
    bucket: "digital" as const,
  },
  manual: {
    name: "Manual",
    website: "https://manualcreative.com",
    country: "USA",
    tags: ["typography", "identity"],
    category: "typography" as const,
    bucket: "typography" as const,
  },
  mucho: {
    name: "Mucho",
    website: "https://wearemucho.com",
    country: "Spain",
    tags: ["identity", "color"],
    category: "color" as const,
    bucket: "visual-identity" as const,
  },
  ordinary: {
    name: "Ordinary",
    website: "https://ordinary.co",
    country: "USA",
    tags: ["typography", "editorial"],
    category: "typography" as const,
    bucket: "typography" as const,
  },
  build: {
    name: "Build",
    website: "https://wearebuild.com",
    country: "UK",
    tags: ["typography", "identity"],
    category: "typography" as const,
    bucket: "typography" as const,
  },
  jetset: {
    name: "Experimental Jetset",
    website: "https://www.experimentaljetset.nl",
    country: "Netherlands",
    tags: ["editorial", "typography"],
    category: "editorial" as const,
    bucket: "typography" as const,
  },
  sagmeisterWalsh: {
    name: "Sagmeister & Walsh",
    website: "https://sagmeisterwalsh.com",
    country: "USA",
    tags: ["identity", "expression"],
    category: "visual-identity" as const,
    bucket: "visual-identity" as const,
  },
  instrument: {
    name: "Instrument",
    website: "https://www.instrument.com",
    country: "USA",
    tags: ["digital", "identity"],
    category: "digital" as const,
    bucket: "digital" as const,
  },
  order: {
    name: "Order",
    website: "https://order.design",
    country: "USA",
    tags: ["identity", "systems"],
    category: "visual-identity" as const,
    bucket: "visual-identity" as const,
  },
  bibliotheque: {
    name: "Bibliothèque",
    website: "https://bibliothequedesign.com",
    country: "UK",
    tags: ["identity", "editorial"],
    category: "editorial" as const,
    bucket: "typography" as const,
  },
  johnsonBanks: {
    name: "johnson banks",
    website: "https://www.johnsonbanks.co.uk",
    country: "UK",
    tags: ["identity", "strategy"],
    category: "visual-identity" as const,
    bucket: "visual-identity" as const,
  },
  spin: {
    name: "Spin",
    website: "https://spin.co.uk",
    country: "UK",
    tags: ["typography", "identity"],
    category: "typography" as const,
    bucket: "typography" as const,
  },
  landor: {
    name: "Landor",
    website: "https://landor.com",
    country: "USA",
    tags: ["branding", "global"],
    category: "visual-identity" as const,
    bucket: "visual-identity" as const,
  },
  wolfOlins: {
    name: "Wolff Olins",
    website: "https://www.wolffolins.com",
    country: "UK",
    tags: ["branding", "strategy"],
    category: "tone-of-voice" as const,
    bucket: "tone-of-voice" as const,
  },
  franklyn: {
    name: "Franklyn",
    website: "https://ohfranklyn.com",
    country: "USA",
    tags: ["identity", "culture"],
    category: "visual-identity" as const,
    bucket: "visual-identity" as const,
  },
  dia: {
    name: "DIA",
    website: "https://dia.tv",
    country: "USA",
    tags: ["motion", "digital"],
    category: "motion" as const,
    bucket: "motion" as const,
  },
  klim: {
    name: "Klim Type Foundry",
    website: "https://klim.co.nz",
    country: "New Zealand",
    tags: ["typography", "type"],
    category: "typography" as const,
    bucket: "typography" as const,
  },
  commercialType: {
    name: "Commercial Type",
    website: "https://commercialtype.com",
    country: "USA",
    tags: ["typography", "type"],
    category: "typography" as const,
    bucket: "typography" as const,
  },
};

export const DEFAULT_REFERENCES = [
  BRAND_REFS.pentagram,
  BRAND_REFS.dumbar,
  BRAND_REFS.collins,
  BRAND_REFS.base,
  BRAND_REFS.manual,
  BRAND_REFS.mucho,
  BRAND_REFS.instrument,
  BRAND_REFS.order,
];

export const INDUSTRY_SUGGESTIONS: Record<IndustryId, SuggestionPool> = {
  architecture: {
    direct: [
      {
        name: "OMA",
        website: "https://www.oma.com",
        country: "Netherlands",
        tags: ["global", "cultural"],
        bucket: "scale",
        reason: {
          en: "International practice of comparable scale and cultural influence",
          ru: "Международное бюро сопоставимого масштаба и культурного влияния",
        },
      },
      {
        name: "Snøhetta",
        website: "https://snohetta.com",
        country: "Norway",
        tags: ["global", "public"],
        bucket: "scale",
      },
      {
        name: "BIG",
        website: "https://big.dk",
        country: "Denmark",
        tags: ["global", "bold"],
        bucket: "scale",
      },
      {
        name: "Foster + Partners",
        website: "https://www.fosterandpartners.com",
        country: "UK",
        tags: ["global", "corporate"],
        bucket: "scale",
      },
      {
        name: "MVRDV",
        website: "https://www.mvrdv.com",
        country: "Netherlands",
        tags: ["experimental", "urban"],
        bucket: "adjacent",
      },
      {
        name: "Norm Architects",
        website: "https://normcph.com",
        country: "Denmark",
        tags: ["minimal", "residential", "premium"],
        bucket: "close",
        reason: {
          en: "Similar minimal approach and premium residential segment",
          ru: "Минималистичный подход и премиальный residential-сегмент",
        },
      },
      {
        name: "UNStudio",
        website: "https://www.unstudio.com",
        country: "Netherlands",
        tags: ["global", "digital"],
        bucket: "adjacent",
      },
      {
        name: "MAD Architects",
        website: "https://www.i-mad.com",
        country: "China",
        tags: ["experimental", "cultural"],
        bucket: "adjacent",
      },
      {
        name: "David Chipperfield",
        website: "https://davidchipperfield.com",
        country: "UK",
        tags: ["minimal", "cultural"],
        bucket: "close",
      },
      {
        name: "Aires Mateus",
        website: "https://www.airesmateus.com",
        country: "Portugal",
        tags: ["minimal", "independent"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.jetset,
      BRAND_REFS.ordinary,
      BRAND_REFS.build,
      BRAND_REFS.manual,
    ],
    keywords: [
      {
        match:
          /hospitality|hotel|restaurant|interior|гостиниц|отел|ресторан|интерьер/i,
        weight: 20,
        bucket: "close",
        tags: ["hospitality", "interior"],
        direct: [
          "Neri&Hu",
          "Space Copenhagen",
          "Yabu Pushelberg",
          "Studio Mumbai",
        ],
      },
      {
        match:
          /minimal|private|house|residential|quiet|жилой|частн|минимал|дом/i,
        weight: 20,
        bucket: "close",
        tags: ["residential", "minimal"],
        direct: [
          "Norm Architects",
          "John Pawson",
          "Aires Mateus",
          "David Chipperfield",
        ],
      },
      {
        match: /cultural|museum|biennale|культур|музей|галере/i,
        weight: 18,
        bucket: "adjacent",
        tags: ["cultural"],
        direct: ["MAD Architects", "OMA", "Snøhetta", "Assemble"],
      },
      {
        match: /experimental|bold|радикал|эксперимент/i,
        weight: 18,
        bucket: "adjacent",
        tags: ["experimental"],
        direct: ["MAD Architects", "MVRDV", "UNStudio", "Assemble"],
      },
      {
        match:
          /sustainable|circular|timber|ecological|устойчив|эколог|дерев/i,
        weight: 20,
        bucket: "close",
        tags: ["sustainable", "timber"],
        direct: [
          "Henning Larsen",
          "White Arkitekter",
          "Lendager",
          "Waugh Thistleton Architects",
        ],
      },
      {
        match: /landscape|ландшафт|garden|сад/i,
        weight: 18,
        bucket: "adjacent",
        tags: ["landscape"],
        direct: ["Gustafson Porter", "West 8", "Michel Desvigne"],
      },
      {
        match: /urban|мастер.?план|урбан|city.?plan/i,
        weight: 18,
        bucket: "adjacent",
        tags: ["urbanism"],
        direct: ["MVRDV", "OMA", "Gehl", "UNStudio"],
      },
      {
        match: /public.?space|общественн|площад/i,
        weight: 16,
        bucket: "regional",
        tags: ["public"],
        direct: ["Snøhetta", "Gehl", "Assemble"],
      },
      {
        match: /restor|реставрац|heritage|памятник/i,
        weight: 16,
        bucket: "close",
        tags: ["restoration"],
        direct: ["David Chipperfield", "Caruso St John", "Jørn Utzon"],
      },
      {
        match: /reconstr|реконструк/i,
        weight: 16,
        bucket: "close",
        tags: ["reconstruction"],
        direct: ["OMA", "David Chipperfield", "Caruso St John"],
      },
      {
        match: /international|global|large|corporate|международ|глобал|крупн/i,
        weight: 15,
        bucket: "scale",
        tags: ["global"],
        direct: ["OMA", "BIG", "Snøhetta", "Foster + Partners"],
      },
      {
        match:
          /independent|boutique|local|studio|независим|локальн|небольш/i,
        exclude: /international|global|корпорат/i,
        weight: 15,
        bucket: "regional",
        tags: ["independent"],
        direct: [
          "Norm Architects",
          "Aires Mateus",
          "John Pawson",
          "Studio Mumbai",
        ],
      },
    ],
  },

  "interior-design": {
    direct: [
      {
        name: "Neri&Hu",
        website: "https://www.neriandhu.com",
        country: "China",
        tags: ["hospitality", "premium"],
        bucket: "close",
      },
      {
        name: "Space Copenhagen",
        website: "https://spacecph.com",
        country: "Denmark",
        tags: ["hospitality", "minimal"],
        bucket: "close",
      },
      {
        name: "Yabu Pushelberg",
        website: "https://www.yabupushelberg.com",
        country: "Canada",
        tags: ["hospitality", "global"],
        bucket: "scale",
      },
      {
        name: "Studio Mumbai",
        website: "https://www.studiomumbai.com",
        country: "India",
        tags: ["craft", "independent"],
        bucket: "regional",
      },
      {
        name: "Kelly Wearstler",
        website: "https://www.kellywearstler.com",
        country: "USA",
        tags: ["residential", "bold"],
        bucket: "adjacent",
      },
      {
        name: "Dimorestudio",
        website: "https://www.dimorestudio.eu",
        country: "Italy",
        tags: ["residential", "premium"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.ordinary,
      BRAND_REFS.build,
      BRAND_REFS.mucho,
    ],
  },

  "real-estate": {
    direct: [
      {
        name: "Related Companies",
        website: "https://www.related.com",
        country: "USA",
        tags: ["developer", "global"],
        bucket: "scale",
      },
      {
        name: "Brookfield Properties",
        website: "https://www.brookfieldproperties.com",
        country: "Canada",
        tags: ["developer", "global"],
        bucket: "scale",
      },
      {
        name: "Compass",
        website: "https://www.compass.com",
        country: "USA",
        tags: ["brokerage", "digital"],
        bucket: "close",
      },
      {
        name: "Sotheby's International Realty",
        website: "https://www.sothebysrealty.com",
        country: "USA",
        tags: ["luxury", "brokerage"],
        bucket: "close",
      },
      {
        name: "Knight Frank",
        website: "https://www.knightfrank.com",
        country: "UK",
        tags: ["advisory", "global"],
        bucket: "scale",
      },
      {
        name: "JLL",
        website: "https://www.jll.com",
        country: "USA",
        tags: ["advisory", "global"],
        bucket: "scale",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.base,
    ],
  },

  construction: {
    direct: [
      {
        name: "Turner Construction",
        website: "https://www.turnerconstruction.com",
        country: "USA",
        tags: ["global", "commercial"],
        bucket: "scale",
      },
      {
        name: "Skanska",
        website: "https://www.skanska.com",
        country: "Sweden",
        tags: ["global", "sustainable"],
        bucket: "scale",
      },
      {
        name: "AECOM",
        website: "https://aecom.com",
        country: "USA",
        tags: ["global", "infrastructure"],
        bucket: "scale",
      },
      {
        name: "Bouygues",
        website: "https://www.bouygues.com",
        country: "France",
        tags: ["global"],
        bucket: "scale",
      },
      {
        name: "Multiplex",
        website: "https://www.multiplex.global",
        country: "Australia",
        tags: ["commercial"],
        bucket: "close",
      },
      {
        name: "Lendlease",
        website: "https://www.lendlease.com",
        country: "Australia",
        tags: ["developer"],
        bucket: "adjacent",
      },
    ],
    references: [BRAND_REFS.pentagram, BRAND_REFS.dumbar, BRAND_REFS.manual],
  },

  technology: {
    direct: [
      {
        name: "Linear",
        website: "https://linear.app",
        country: "USA",
        tags: ["saas", "b2b"],
        bucket: "close",
      },
      {
        name: "Notion",
        website: "https://www.notion.com",
        country: "USA",
        tags: ["saas", "productivity"],
        bucket: "close",
      },
      {
        name: "Figma",
        website: "https://www.figma.com",
        country: "USA",
        tags: ["saas", "design"],
        bucket: "close",
      },
      {
        name: "Stripe",
        website: "https://stripe.com",
        country: "USA",
        tags: ["fintech", "infrastructure"],
        bucket: "adjacent",
      },
      {
        name: "Vercel",
        website: "https://vercel.com",
        country: "USA",
        tags: ["developer", "platform"],
        bucket: "close",
      },
      {
        name: "Arc",
        website: "https://arc.net",
        country: "USA",
        tags: ["consumer", "browser"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.base,
      BRAND_REFS.manual,
      BRAND_REFS.mucho,
    ],
    keywords: [
      {
        match:
          /\b(ai|artificial intelligence|machine learning|ml|agentic)\b|искусственн|нейросет|машинн.?обуч/i,
        weight: 20,
        bucket: "close",
        tags: ["ai"],
        direct: ["OpenAI", "Anthropic", "Perplexity", "Hugging Face"],
      },
    ],
  },

  "artificial-intelligence": {
    direct: [
      {
        name: "OpenAI",
        website: "https://openai.com",
        country: "USA",
        tags: ["foundation", "global"],
        bucket: "scale",
      },
      {
        name: "Anthropic",
        website: "https://www.anthropic.com",
        country: "USA",
        tags: ["foundation", "safety"],
        bucket: "close",
      },
      {
        name: "Perplexity",
        website: "https://www.perplexity.ai",
        country: "USA",
        tags: ["search", "consumer"],
        bucket: "close",
      },
      {
        name: "Hugging Face",
        website: "https://huggingface.co",
        country: "USA",
        tags: ["open-source", "platform"],
        bucket: "adjacent",
      },
      {
        name: "Cohere",
        website: "https://cohere.com",
        country: "Canada",
        tags: ["enterprise", "b2b"],
        bucket: "close",
      },
      {
        name: "Mistral",
        website: "https://mistral.ai",
        country: "France",
        tags: ["foundation", "european"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.base,
    ],
  },

  software: {
    direct: [
      {
        name: "Linear",
        website: "https://linear.app",
        country: "USA",
        tags: ["saas", "b2b"],
        bucket: "close",
      },
      {
        name: "Notion",
        website: "https://www.notion.com",
        country: "USA",
        tags: ["saas", "productivity"],
        bucket: "close",
      },
      {
        name: "Figma",
        website: "https://www.figma.com",
        country: "USA",
        tags: ["design", "saas"],
        bucket: "close",
      },
      {
        name: "Slack",
        website: "https://slack.com",
        country: "USA",
        tags: ["collaboration", "global"],
        bucket: "scale",
      },
      {
        name: "Asana",
        website: "https://asana.com",
        country: "USA",
        tags: ["productivity", "b2b"],
        bucket: "close",
      },
      {
        name: "Airtable",
        website: "https://www.airtable.com",
        country: "USA",
        tags: ["platform", "saas"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.base,
      BRAND_REFS.manual,
    ],
  },

  finance: {
    direct: [
      {
        name: "Stripe",
        website: "https://stripe.com",
        country: "USA",
        tags: ["payments", "b2b"],
        bucket: "close",
      },
      {
        name: "Revolut",
        website: "https://www.revolut.com",
        country: "UK",
        tags: ["neobank", "consumer"],
        bucket: "close",
      },
      {
        name: "Wise",
        website: "https://wise.com",
        country: "UK",
        tags: ["transfers", "global"],
        bucket: "close",
      },
      {
        name: "Robinhood",
        website: "https://robinhood.com",
        country: "USA",
        tags: ["brokerage", "consumer"],
        bucket: "adjacent",
      },
      {
        name: "Plaid",
        website: "https://plaid.com",
        country: "USA",
        tags: ["infrastructure", "b2b"],
        bucket: "adjacent",
      },
      {
        name: "Klarna",
        website: "https://www.klarna.com",
        country: "Sweden",
        tags: ["payments", "consumer"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.mucho,
    ],
  },

  healthcare: {
    direct: [
      {
        name: "One Medical",
        website: "https://www.onemedical.com",
        country: "USA",
        tags: ["clinic", "consumer"],
        bucket: "close",
      },
      {
        name: "Oscar Health",
        website: "https://www.hioscar.com",
        country: "USA",
        tags: ["insurance", "digital"],
        bucket: "close",
      },
      {
        name: "Ro",
        website: "https://ro.co",
        country: "USA",
        tags: ["telehealth", "dtc"],
        bucket: "close",
      },
      {
        name: "Hims",
        website: "https://www.hims.com",
        country: "USA",
        tags: ["telehealth", "dtc"],
        bucket: "adjacent",
      },
      {
        name: "Teladoc",
        website: "https://www.teladoc.com",
        country: "USA",
        tags: ["telehealth", "global"],
        bucket: "scale",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.base,
      BRAND_REFS.manual,
    ],
  },

  "beauty-wellness": {
    direct: [
      {
        name: "Aesop",
        website: "https://www.aesop.com",
        country: "Australia",
        tags: ["premium", "retail"],
        bucket: "close",
      },
      {
        name: "The Ordinary",
        website: "https://theordinary.com",
        country: "Canada",
        tags: ["accessible", "skincare"],
        bucket: "close",
      },
      {
        name: "Glossier",
        website: "https://www.glossier.com",
        country: "USA",
        tags: ["dtc", "beauty"],
        bucket: "close",
      },
      {
        name: "Le Labo",
        website: "https://www.lelabofragrances.com",
        country: "USA",
        tags: ["fragrance", "premium"],
        bucket: "adjacent",
      },
      {
        name: "Byredo",
        website: "https://www.byredo.com",
        country: "Sweden",
        tags: ["fragrance", "luxury"],
        bucket: "adjacent",
      },
      {
        name: "Rituals",
        website: "https://www.rituals.com",
        country: "Netherlands",
        tags: ["wellness", "retail"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.ordinary,
      BRAND_REFS.mucho,
    ],
  },

  fashion: {
    direct: [
      {
        name: "COS",
        website: "https://www.cos.com",
        country: "Sweden",
        tags: ["minimal", "retail"],
        bucket: "close",
      },
      {
        name: "Acne Studios",
        website: "https://www.acnestudios.com",
        country: "Sweden",
        tags: ["premium", "fashion"],
        bucket: "close",
      },
      {
        name: "Everlane",
        website: "https://www.everlane.com",
        country: "USA",
        tags: ["dtc", "accessible"],
        bucket: "close",
      },
      {
        name: "Toteme",
        website: "https://toteme.com",
        country: "Sweden",
        tags: ["minimal", "premium"],
        bucket: "close",
      },
      {
        name: "Arket",
        website: "https://www.arket.com",
        country: "Sweden",
        tags: ["lifestyle", "retail"],
        bucket: "adjacent",
      },
      {
        name: "Our Legacy",
        website: "https://www.ourlegacy.com",
        country: "Sweden",
        tags: ["independent", "premium"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.ordinary,
      BRAND_REFS.build,
    ],
  },

  "food-beverage": {
    direct: [
      {
        name: "Blue Bottle",
        website: "https://bluebottlecoffee.com",
        country: "USA",
        tags: ["coffee", "premium"],
        bucket: "close",
      },
      {
        name: "Tim Wendelboe",
        website: "https://www.timwendelboe.no",
        country: "Norway",
        tags: ["coffee", "specialty"],
        bucket: "close",
      },
      {
        name: "April Coffee",
        website: "https://aprilcoffeeroasters.com",
        country: "Denmark",
        tags: ["coffee", "specialty"],
        bucket: "close",
      },
      {
        name: "La Cabra",
        website: "https://lacabra.dk",
        country: "Denmark",
        tags: ["coffee", "specialty"],
        bucket: "regional",
      },
      {
        name: "Square Mile",
        website: "https://shop.squaremilecoffee.com",
        country: "UK",
        tags: ["coffee", "specialty"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.ordinary,
      BRAND_REFS.mucho,
    ],
    keywords: [
      {
        match: /coffee|roast|café|cafe|кофе|обжар/i,
        weight: 20,
        bucket: "close",
        tags: ["coffee"],
        direct: [
          "Blue Bottle",
          "Tim Wendelboe",
          "April Coffee",
          "La Cabra",
          "Square Mile",
        ],
      },
      {
        match: /barber|groom|hair|барбер|парикмах/i,
        weight: 18,
        bucket: "adjacent",
        tags: ["grooming"],
        direct: ["Blind Barber", "Schorem", "Fellow Barber"],
      },
    ],
  },

  hospitality: {
    direct: [
      {
        name: "Ace Hotel",
        website: "https://acehotel.com",
        country: "USA",
        tags: ["boutique", "lifestyle"],
        bucket: "close",
      },
      {
        name: "Soho House",
        website: "https://www.sohohouse.com",
        country: "UK",
        tags: ["members", "premium"],
        bucket: "close",
      },
      {
        name: "Edition",
        website: "https://www.editionhotels.com",
        country: "USA",
        tags: ["luxury", "global"],
        bucket: "scale",
      },
      {
        name: "The Standard",
        website: "https://www.standardhotels.com",
        country: "USA",
        tags: ["boutique", "urban"],
        bucket: "close",
      },
      {
        name: "Aman",
        website: "https://www.aman.com",
        country: "Singapore",
        tags: ["luxury", "global"],
        bucket: "scale",
      },
      {
        name: "Nobu Hotels",
        website: "https://www.nobuhotels.com",
        country: "USA",
        tags: ["luxury", "hospitality"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.ordinary,
      BRAND_REFS.build,
    ],
  },

  travel: {
    direct: [
      {
        name: "Airbnb",
        website: "https://www.airbnb.com",
        country: "USA",
        tags: ["platform", "global"],
        bucket: "scale",
      },
      {
        name: "Kayak",
        website: "https://www.kayak.com",
        country: "USA",
        tags: ["search", "digital"],
        bucket: "close",
      },
      {
        name: "Booking.com",
        website: "https://www.booking.com",
        country: "Netherlands",
        tags: ["platform", "global"],
        bucket: "scale",
      },
      {
        name: "Away",
        website: "https://www.awaytravel.com",
        country: "USA",
        tags: ["luggage", "dtc"],
        bucket: "adjacent",
      },
      {
        name: "Monocle",
        website: "https://monocle.com",
        country: "UK",
        tags: ["editorial", "travel"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.base,
      BRAND_REFS.manual,
    ],
  },

  retail: {
    direct: [
      {
        name: "COS",
        website: "https://www.cos.com",
        country: "Sweden",
        tags: ["fashion", "minimal"],
        bucket: "close",
      },
      {
        name: "Arket",
        website: "https://www.arket.com",
        country: "Sweden",
        tags: ["lifestyle", "retail"],
        bucket: "close",
      },
      {
        name: "Aesop",
        website: "https://www.aesop.com",
        country: "Australia",
        tags: ["beauty", "premium"],
        bucket: "adjacent",
      },
      {
        name: "Muji",
        website: "https://www.muji.com",
        country: "Japan",
        tags: ["lifestyle", "minimal"],
        bucket: "close",
      },
      {
        name: "Everlane",
        website: "https://www.everlane.com",
        country: "USA",
        tags: ["dtc", "fashion"],
        bucket: "close",
      },
      {
        name: "SSENSE",
        website: "https://www.ssense.com",
        country: "Canada",
        tags: ["luxury", "e-commerce"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.ordinary,
      BRAND_REFS.mucho,
    ],
  },

  "e-commerce": {
    direct: [
      {
        name: "Shopify",
        website: "https://www.shopify.com",
        country: "Canada",
        tags: ["platform", "b2b"],
        bucket: "close",
      },
      {
        name: "Stripe",
        website: "https://stripe.com",
        country: "USA",
        tags: ["payments", "infrastructure"],
        bucket: "adjacent",
      },
      {
        name: "Glossier",
        website: "https://www.glossier.com",
        country: "USA",
        tags: ["dtc", "beauty"],
        bucket: "close",
      },
      {
        name: "Away",
        website: "https://www.awaytravel.com",
        country: "USA",
        tags: ["dtc", "product"],
        bucket: "close",
      },
      {
        name: "Everlane",
        website: "https://www.everlane.com",
        country: "USA",
        tags: ["dtc", "fashion"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.base,
      BRAND_REFS.manual,
    ],
  },

  education: {
    direct: [
      {
        name: "Coursera",
        website: "https://www.coursera.org",
        country: "USA",
        tags: ["platform", "global"],
        bucket: "scale",
      },
      {
        name: "MasterClass",
        website: "https://www.masterclass.com",
        country: "USA",
        tags: ["premium", "video"],
        bucket: "close",
      },
      {
        name: "Khan Academy",
        website: "https://www.khanacademy.org",
        country: "USA",
        tags: ["nonprofit", "accessible"],
        bucket: "adjacent",
      },
      {
        name: "Duolingo",
        website: "https://www.duolingo.com",
        country: "USA",
        tags: ["language", "consumer"],
        bucket: "close",
      },
      {
        name: "Skillshare",
        website: "https://www.skillshare.com",
        country: "USA",
        tags: ["creative", "platform"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.base,
    ],
  },

  media: {
    direct: [
      {
        name: "Monocle",
        website: "https://monocle.com",
        country: "UK",
        tags: ["editorial", "premium"],
        bucket: "close",
      },
      {
        name: "The Atlantic",
        website: "https://www.theatlantic.com",
        country: "USA",
        tags: ["editorial", "digital"],
        bucket: "close",
      },
      {
        name: "Pitchfork",
        website: "https://pitchfork.com",
        country: "USA",
        tags: ["music", "editorial"],
        bucket: "adjacent",
      },
      {
        name: "Spotify",
        website: "https://www.spotify.com",
        country: "Sweden",
        tags: ["audio", "platform"],
        bucket: "adjacent",
      },
      {
        name: "Substack",
        website: "https://substack.com",
        country: "USA",
        tags: ["publishing", "platform"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.jetset,
      BRAND_REFS.ordinary,
    ],
  },

  entertainment: {
    direct: [
      {
        name: "Spotify",
        website: "https://www.spotify.com",
        country: "Sweden",
        tags: ["audio", "global"],
        bucket: "scale",
      },
      {
        name: "Netflix",
        website: "https://www.netflix.com",
        country: "USA",
        tags: ["streaming", "global"],
        bucket: "scale",
      },
      {
        name: "Disney",
        website: "https://www.disney.com",
        country: "USA",
        tags: ["media", "global"],
        bucket: "scale",
      },
      {
        name: "Twitch",
        website: "https://www.twitch.tv",
        country: "USA",
        tags: ["live", "community"],
        bucket: "close",
      },
      {
        name: "Patreon",
        website: "https://www.patreon.com",
        country: "USA",
        tags: ["creator", "platform"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.mucho,
    ],
  },

  "culture-arts": {
    direct: [
      {
        name: "Tate",
        website: "https://www.tate.org.uk",
        country: "UK",
        tags: ["museum", "cultural"],
        bucket: "close",
      },
      {
        name: "MoMA",
        website: "https://www.moma.org",
        country: "USA",
        tags: ["museum", "cultural"],
        bucket: "close",
      },
      {
        name: "Serpentine",
        website: "https://www.serpentinegalleries.org",
        country: "UK",
        tags: ["gallery", "contemporary"],
        bucket: "close",
      },
      {
        name: "Palais de Tokyo",
        website: "https://palaisdetokyo.com",
        country: "France",
        tags: ["gallery", "contemporary"],
        bucket: "regional",
      },
      {
        name: "Hauser & Wirth",
        website: "https://www.hauserwirth.com",
        country: "Switzerland",
        tags: ["gallery", "global"],
        bucket: "scale",
      },
      {
        name: "Art Basel",
        website: "https://www.artbasel.com",
        country: "Switzerland",
        tags: ["fair", "global"],
        bucket: "scale",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.dumbar,
      BRAND_REFS.jetset,
      BRAND_REFS.ordinary,
    ],
  },

  "creative-services": {
    direct: [
      {
        name: "Pentagram",
        website: "https://www.pentagram.com",
        country: "USA",
        tags: ["identity", "global"],
        bucket: "scale",
      },
      {
        name: "Collins",
        website: "https://www.wearecollins.com",
        country: "USA",
        tags: ["identity", "strategy"],
        bucket: "close",
      },
      {
        name: "Base Design",
        website: "https://basedesign.com",
        country: "Belgium",
        tags: ["identity", "digital"],
        bucket: "close",
      },
      {
        name: "Manual",
        website: "https://manualcreative.com",
        country: "USA",
        tags: ["identity", "typography"],
        bucket: "close",
      },
      {
        name: "Mucho",
        website: "https://wearemucho.com",
        country: "Spain",
        tags: ["identity", "independent"],
        bucket: "regional",
      },
      {
        name: "Sagmeister & Walsh",
        website: "https://sagmeisterwalsh.com",
        country: "USA",
        tags: ["identity", "expression"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.dumbar,
      BRAND_REFS.jetset,
      BRAND_REFS.ordinary,
      BRAND_REFS.build,
    ],
  },

  "professional-services": {
    direct: [
      {
        name: "McKinsey",
        website: "https://www.mckinsey.com",
        country: "USA",
        tags: ["consulting", "global"],
        bucket: "scale",
      },
      {
        name: "IDEO",
        website: "https://www.ideo.com",
        country: "USA",
        tags: ["design", "innovation"],
        bucket: "close",
      },
      {
        name: "Accenture",
        website: "https://www.accenture.com",
        country: "Ireland",
        tags: ["consulting", "global"],
        bucket: "scale",
      },
      {
        name: "Deloitte",
        website: "https://www.deloitte.com",
        country: "UK",
        tags: ["consulting", "global"],
        bucket: "scale",
      },
      {
        name: "BCG",
        website: "https://www.bcg.com",
        country: "USA",
        tags: ["consulting", "global"],
        bucket: "scale",
      },
      {
        name: "Frog",
        website: "https://www.frog.co",
        country: "USA",
        tags: ["design", "innovation"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.base,
    ],
  },

  "clean-energy": {
    direct: [
      {
        name: "Tesla Energy",
        website: "https://www.tesla.com/energy",
        country: "USA",
        tags: ["storage", "global"],
        bucket: "scale",
      },
      {
        name: "Sunrun",
        website: "https://www.sunrun.com",
        country: "USA",
        tags: ["solar", "residential"],
        bucket: "close",
      },
      {
        name: "Octopus Energy",
        website: "https://octopus.energy",
        country: "UK",
        tags: ["utility", "retail"],
        bucket: "close",
      },
      {
        name: "Enphase",
        website: "https://enphase.com",
        country: "USA",
        tags: ["hardware", "solar"],
        bucket: "close",
      },
      {
        name: "Sonnen",
        website: "https://sonnen.de",
        country: "Germany",
        tags: ["storage", "european"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.base,
      {
        name: "Nest",
        website: "https://store.google.com/category/connected_home",
        country: "USA",
        tags: ["smart-home", "product"],
        category: "digital",
        bucket: "digital",
        reason: {
          en: "Reference for product UI and calm smart-home aesthetics",
          ru: "Ориентир по продуктовому UI и спокойной smart-home эстетике",
        },
      },
    ],
  },

  automotive: {
    direct: [
      {
        name: "Tesla",
        website: "https://www.tesla.com",
        country: "USA",
        tags: ["ev", "global"],
        bucket: "scale",
      },
      {
        name: "Rivian",
        website: "https://rivian.com",
        country: "USA",
        tags: ["ev", "adventure"],
        bucket: "close",
      },
      {
        name: "Polestar",
        website: "https://www.polestar.com",
        country: "Sweden",
        tags: ["ev", "premium"],
        bucket: "close",
      },
      {
        name: "BMW",
        website: "https://www.bmw.com",
        country: "Germany",
        tags: ["premium", "global"],
        bucket: "scale",
      },
      {
        name: "Porsche",
        website: "https://www.porsche.com",
        country: "Germany",
        tags: ["luxury", "performance"],
        bucket: "adjacent",
      },
      {
        name: "Lucid",
        website: "https://www.lucidmotors.com",
        country: "USA",
        tags: ["ev", "luxury"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.dumbar,
      BRAND_REFS.manual,
    ],
  },

  "consumer-products": {
    direct: [
      {
        name: "Muji",
        website: "https://www.muji.com",
        country: "Japan",
        tags: ["minimal", "lifestyle"],
        bucket: "close",
      },
      {
        name: "Aesop",
        website: "https://www.aesop.com",
        country: "Australia",
        tags: ["premium", "retail"],
        bucket: "adjacent",
      },
      {
        name: "Dyson",
        website: "https://www.dyson.com",
        country: "UK",
        tags: ["hardware", "premium"],
        bucket: "close",
      },
      {
        name: "Bang & Olufsen",
        website: "https://www.bang-olufsen.com",
        country: "Denmark",
        tags: ["audio", "luxury"],
        bucket: "adjacent",
      },
      {
        name: "Teenage Engineering",
        website: "https://teenage.engineering",
        country: "Sweden",
        tags: ["hardware", "design"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.ordinary,
      BRAND_REFS.dumbar,
      BRAND_REFS.mucho,
    ],
  },

  nonprofit: {
    direct: [
      {
        name: "charity: water",
        website: "https://www.charitywater.org",
        country: "USA",
        tags: ["impact", "water"],
        bucket: "close",
      },
      {
        name: "Wikipedia",
        website: "https://www.wikipedia.org",
        country: "USA",
        tags: ["knowledge", "platform"],
        bucket: "adjacent",
      },
      {
        name: "Red Cross",
        website: "https://www.icrc.org",
        country: "Switzerland",
        tags: ["humanitarian", "global"],
        bucket: "scale",
      },
      {
        name: "WWF",
        website: "https://www.worldwildlife.org",
        country: "Switzerland",
        tags: ["environment", "global"],
        bucket: "scale",
      },
      {
        name: "Amnesty International",
        website: "https://www.amnesty.org",
        country: "UK",
        tags: ["rights", "global"],
        bucket: "scale",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.manual,
      BRAND_REFS.base,
    ],
  },

  "advertising-marketing": {
    direct: [
      {
        name: "Wieden+Kennedy",
        website: "https://www.wk.com",
        country: "USA",
        tags: ["creative", "global"],
        bucket: "scale",
      },
      {
        name: "Droga5",
        website: "https://droga5.com",
        country: "USA",
        tags: ["creative", "brand"],
        bucket: "close",
      },
      {
        name: "Mother",
        website: "https://mother.xyz",
        country: "UK",
        tags: ["independent", "creative"],
        bucket: "close",
      },
      {
        name: "Anomaly",
        website: "https://anomaly.com",
        country: "USA",
        tags: ["creative", "strategy"],
        bucket: "close",
      },
      {
        name: "R/GA",
        website: "https://www.rga.com",
        country: "USA",
        tags: ["digital", "global"],
        bucket: "scale",
      },
      {
        name: "72andSunny",
        website: "https://www.72andsunny.com",
        country: "USA",
        tags: ["creative", "culture"],
        bucket: "adjacent",
      },
      {
        name: "BBDO",
        website: "https://www.bbdo.com",
        country: "USA",
        tags: ["global", "network"],
        bucket: "scale",
      },
      {
        name: "Ogilvy",
        website: "https://www.ogilvy.com",
        country: "USA",
        tags: ["global", "brand"],
        bucket: "scale",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.instrument,
      BRAND_REFS.franklyn,
      BRAND_REFS.dia,
      BRAND_REFS.wolfOlins,
    ],
  },
  agriculture: {
    direct: [
      {
        name: "John Deere",
        website: "https://www.deere.com",
        country: "USA",
        tags: ["equipment", "global"],
        bucket: "scale",
      },
      {
        name: "Bayer Crop Science",
        website: "https://www.bayer.com",
        country: "Germany",
        tags: ["agritech", "global"],
        bucket: "scale",
      },
      {
        name: "Syngenta",
        website: "https://www.syngenta.com",
        country: "Switzerland",
        tags: ["agritech", "global"],
        bucket: "scale",
      },
      {
        name: "Indigo Ag",
        website: "https://www.indigoag.com",
        country: "USA",
        tags: ["agritech", "sustainable"],
        bucket: "close",
      },
      {
        name: "Farmers Business Network",
        website: "https://www.fbn.com",
        country: "USA",
        tags: ["platform", "data"],
        bucket: "adjacent",
      },
      {
        name: "Yara",
        website: "https://www.yara.com",
        country: "Norway",
        tags: ["nutrition", "global"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.landor,
      BRAND_REFS.manual,
    ],
  },
  aviation: {
    direct: [
      {
        name: "Boeing",
        website: "https://www.boeing.com",
        country: "USA",
        tags: ["aerospace", "global"],
        bucket: "scale",
      },
      {
        name: "Airbus",
        website: "https://www.airbus.com",
        country: "France",
        tags: ["aerospace", "global"],
        bucket: "scale",
      },
      {
        name: "SpaceX",
        website: "https://www.spacex.com",
        country: "USA",
        tags: ["space", "engineering"],
        bucket: "adjacent",
      },
      {
        name: "Embraer",
        website: "https://embraer.com",
        country: "Brazil",
        tags: ["aircraft", "regional"],
        bucket: "regional",
      },
      {
        name: "Bombardier",
        website: "https://bombardier.com",
        country: "Canada",
        tags: ["aviation", "transport"],
        bucket: "close",
      },
      {
        name: "Rolls-Royce",
        website: "https://www.rolls-royce.com",
        country: "UK",
        tags: ["engines", "engineering"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.landor,
      BRAND_REFS.wolfOlins,
      BRAND_REFS.base,
    ],
  },
  biotech: {
    direct: [
      {
        name: "Moderna",
        website: "https://www.modernatx.com",
        country: "USA",
        tags: ["biotech", "mrna"],
        bucket: "scale",
      },
      {
        name: "Amgen",
        website: "https://www.amgen.com",
        country: "USA",
        tags: ["biotech", "global"],
        bucket: "scale",
      },
      {
        name: "Genentech",
        website: "https://www.gene.com",
        country: "USA",
        tags: ["biotech", "research"],
        bucket: "close",
      },
      {
        name: "CRISPR Therapeutics",
        website: "https://crisprtx.com",
        country: "Switzerland",
        tags: ["gene", "research"],
        bucket: "close",
      },
      {
        name: "Illumina",
        website: "https://www.illumina.com",
        country: "USA",
        tags: ["genomics", "tools"],
        bucket: "adjacent",
      },
      {
        name: "BioNTech",
        website: "https://www.biontech.com",
        country: "Germany",
        tags: ["biotech", "mrna"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.instrument,
      BRAND_REFS.order,
    ],
  },
  "climate-tech": {
    direct: [
      {
        name: "Stripe Climate",
        website: "https://stripe.com/climate",
        country: "USA",
        tags: ["carbon", "platform"],
        bucket: "adjacent",
      },
      {
        name: "Climeworks",
        website: "https://climeworks.com",
        country: "Switzerland",
        tags: ["carbon", "capture"],
        bucket: "close",
      },
      {
        name: "Watershed",
        website: "https://watershed.com",
        country: "USA",
        tags: ["carbon", "software"],
        bucket: "close",
      },
      {
        name: "Pachama",
        website: "https://pachama.com",
        country: "USA",
        tags: ["carbon", "nature"],
        bucket: "close",
      },
      {
        name: "Northvolt",
        website: "https://northvolt.com",
        country: "Sweden",
        tags: ["batteries", "energy"],
        bucket: "regional",
      },
      {
        name: "Ørsted",
        website: "https://orsted.com",
        country: "Denmark",
        tags: ["renewable", "energy"],
        bucket: "scale",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.dumbar,
      BRAND_REFS.manual,
    ],
  },
  consulting: {
    direct: [
      {
        name: "McKinsey & Company",
        website: "https://www.mckinsey.com",
        country: "USA",
        tags: ["strategy", "global"],
        bucket: "scale",
      },
      {
        name: "Boston Consulting Group",
        website: "https://www.bcg.com",
        country: "USA",
        tags: ["strategy", "global"],
        bucket: "scale",
      },
      {
        name: "Bain & Company",
        website: "https://www.bain.com",
        country: "USA",
        tags: ["strategy", "global"],
        bucket: "scale",
      },
      {
        name: "Accenture",
        website: "https://www.accenture.com",
        country: "Ireland",
        tags: ["digital", "services"],
        bucket: "adjacent",
      },
      {
        name: "Deloitte",
        website: "https://www.deloitte.com",
        country: "UK",
        tags: ["advisory", "global"],
        bucket: "scale",
      },
      {
        name: "IDEO",
        website: "https://www.ideo.com",
        country: "USA",
        tags: ["design", "innovation"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.wolfOlins,
      BRAND_REFS.landor,
      BRAND_REFS.collins,
      BRAND_REFS.order,
    ],
  },
  cybersecurity: {
    direct: [
      {
        name: "CrowdStrike",
        website: "https://www.crowdstrike.com",
        country: "USA",
        tags: ["security", "endpoint"],
        bucket: "scale",
      },
      {
        name: "Palo Alto Networks",
        website: "https://www.paloaltonetworks.com",
        country: "USA",
        tags: ["security", "network"],
        bucket: "scale",
      },
      {
        name: "Okta",
        website: "https://www.okta.com",
        country: "USA",
        tags: ["identity", "security"],
        bucket: "close",
      },
      {
        name: "1Password",
        website: "https://1password.com",
        country: "Canada",
        tags: ["security", "consumer"],
        bucket: "close",
      },
      {
        name: "Cloudflare",
        website: "https://www.cloudflare.com",
        country: "USA",
        tags: ["security", "edge"],
        bucket: "adjacent",
      },
      {
        name: "Nord Security",
        website: "https://nordsecurity.com",
        country: "Lithuania",
        tags: ["vpn", "consumer"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.instrument,
      BRAND_REFS.base,
      BRAND_REFS.order,
    ],
  },
  "fitness-sports": {
    direct: [
      {
        name: "Nike",
        website: "https://www.nike.com",
        country: "USA",
        tags: ["sports", "global"],
        bucket: "scale",
      },
      {
        name: "Adidas",
        website: "https://www.adidas.com",
        country: "Germany",
        tags: ["sports", "global"],
        bucket: "scale",
      },
      {
        name: "Lululemon",
        website: "https://www.lululemon.com",
        country: "Canada",
        tags: ["fitness", "premium"],
        bucket: "close",
      },
      {
        name: "Peloton",
        website: "https://www.onepeloton.com",
        country: "USA",
        tags: ["fitness", "digital"],
        bucket: "close",
      },
      {
        name: "Whoop",
        website: "https://www.whoop.com",
        country: "USA",
        tags: ["wearable", "performance"],
        bucket: "adjacent",
      },
      {
        name: "Gymshark",
        website: "https://www.gymshark.com",
        country: "UK",
        tags: ["fitness", "dtc"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.franklyn,
      BRAND_REFS.mucho,
      BRAND_REFS.dia,
    ],
  },
  gaming: {
    direct: [
      {
        name: "Epic Games",
        website: "https://www.epicgames.com",
        country: "USA",
        tags: ["games", "platform"],
        bucket: "scale",
      },
      {
        name: "Riot Games",
        website: "https://www.riotgames.com",
        country: "USA",
        tags: ["games", "esports"],
        bucket: "close",
      },
      {
        name: "Valve",
        website: "https://www.valvesoftware.com",
        country: "USA",
        tags: ["games", "platform"],
        bucket: "scale",
      },
      {
        name: "Ubisoft",
        website: "https://www.ubisoft.com",
        country: "France",
        tags: ["games", "global"],
        bucket: "scale",
      },
      {
        name: "Supercell",
        website: "https://supercell.com",
        country: "Finland",
        tags: ["mobile", "games"],
        bucket: "regional",
      },
      {
        name: "Roblox",
        website: "https://www.roblox.com",
        country: "USA",
        tags: ["platform", "ugc"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.instrument,
      BRAND_REFS.dia,
      BRAND_REFS.franklyn,
      BRAND_REFS.base,
      BRAND_REFS.pentagram,
    ],
  },
  government: {
    direct: [
      {
        name: "Gov.uk",
        website: "https://www.gov.uk",
        country: "UK",
        tags: ["public", "digital"],
        bucket: "close",
        reason: {
          en: "Benchmark for clear public-sector service design",
          ru: "Ориентир ясного digital-дизайна госсектора",
        },
      },
      {
        name: "US Digital Service",
        website: "https://www.usds.gov",
        country: "USA",
        tags: ["public", "digital"],
        bucket: "close",
      },
      {
        name: "18F",
        website: "https://18f.gsa.gov",
        country: "USA",
        tags: ["public", "product"],
        bucket: "adjacent",
      },
      {
        name: "Singapore Government",
        website: "https://www.gov.sg",
        country: "Singapore",
        tags: ["public", "digital"],
        bucket: "regional",
      },
      {
        name: "Canada.ca",
        website: "https://www.canada.ca",
        country: "Canada",
        tags: ["public", "services"],
        bucket: "scale",
      },
      {
        name: "Designit",
        website: "https://www.designit.com",
        country: "Denmark",
        tags: ["service", "design"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.johnsonBanks,
      BRAND_REFS.bibliotheque,
      BRAND_REFS.spin,
      BRAND_REFS.ordinary,
    ],
  },
  "home-living": {
    direct: [
      {
        name: "IKEA",
        website: "https://www.ikea.com",
        country: "Sweden",
        tags: ["furniture", "global"],
        bucket: "scale",
      },
      {
        name: "West Elm",
        website: "https://www.westelm.com",
        country: "USA",
        tags: ["furniture", "lifestyle"],
        bucket: "close",
      },
      {
        name: "HAY",
        website: "https://hay.com",
        country: "Denmark",
        tags: ["design", "furniture"],
        bucket: "close",
      },
      {
        name: "Muuto",
        website: "https://www.muuto.com",
        country: "Denmark",
        tags: ["design", "scandinavian"],
        bucket: "regional",
      },
      {
        name: "Article",
        website: "https://www.article.com",
        country: "Canada",
        tags: ["furniture", "dtc"],
        bucket: "adjacent",
      },
      {
        name: "Restoration Hardware",
        website: "https://rh.com",
        country: "USA",
        tags: ["luxury", "home"],
        bucket: "scale",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.manual,
      BRAND_REFS.mucho,
      BRAND_REFS.ordinary,
      BRAND_REFS.bibliotheque,
    ],
  },
  insurance: {
    direct: [
      {
        name: "Lemonade",
        website: "https://www.lemonade.com",
        country: "USA",
        tags: ["insurtech", "dtc"],
        bucket: "close",
      },
      {
        name: "Allstate",
        website: "https://www.allstate.com",
        country: "USA",
        tags: ["insurance", "scale"],
        bucket: "scale",
      },
      {
        name: "AXA",
        website: "https://www.axa.com",
        country: "France",
        tags: ["insurance", "global"],
        bucket: "scale",
      },
      {
        name: "Root Insurance",
        website: "https://www.joinroot.com",
        country: "USA",
        tags: ["insurtech", "auto"],
        bucket: "close",
      },
      {
        name: "Policygenius",
        website: "https://www.policygenius.com",
        country: "USA",
        tags: ["marketplace", "insurance"],
        bucket: "adjacent",
      },
      {
        name: "Zurich Insurance",
        website: "https://www.zurich.com",
        country: "Switzerland",
        tags: ["insurance", "global"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.landor,
      BRAND_REFS.collins,
      BRAND_REFS.instrument,
    ],
  },
  "jewelry-luxury": {
    direct: [
      {
        name: "Cartier",
        website: "https://www.cartier.com",
        country: "France",
        tags: ["luxury", "jewelry"],
        bucket: "scale",
      },
      {
        name: "Tiffany & Co.",
        website: "https://www.tiffany.com",
        country: "USA",
        tags: ["luxury", "jewelry"],
        bucket: "scale",
      },
      {
        name: "Mejuri",
        website: "https://mejuri.com",
        country: "Canada",
        tags: ["jewelry", "dtc"],
        bucket: "close",
      },
      {
        name: "Monica Vinader",
        website: "https://www.monicavinader.com",
        country: "UK",
        tags: ["jewelry", "premium"],
        bucket: "close",
      },
      {
        name: "Bulgari",
        website: "https://www.bulgari.com",
        country: "Italy",
        tags: ["luxury", "jewelry"],
        bucket: "scale",
      },
      {
        name: "Pandora",
        website: "https://www.pandora.net",
        country: "Denmark",
        tags: ["jewelry", "accessible"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.manual,
      BRAND_REFS.mucho,
      BRAND_REFS.spin,
      BRAND_REFS.bibliotheque,
    ],
  },
  legal: {
    direct: [
      {
        name: "Clifford Chance",
        website: "https://www.cliffordchance.com",
        country: "UK",
        tags: ["law", "global"],
        bucket: "scale",
      },
      {
        name: "Linklaters",
        website: "https://www.linklaters.com",
        country: "UK",
        tags: ["law", "global"],
        bucket: "scale",
      },
      {
        name: "Kirkland & Ellis",
        website: "https://www.kirkland.com",
        country: "USA",
        tags: ["law", "corporate"],
        bucket: "scale",
      },
      {
        name: "LegalZoom",
        website: "https://www.legalzoom.com",
        country: "USA",
        tags: ["legaltech", "consumer"],
        bucket: "adjacent",
      },
      {
        name: "Clio",
        website: "https://www.clio.com",
        country: "Canada",
        tags: ["legaltech", "software"],
        bucket: "close",
      },
      {
        name: "A&O Shearman",
        website: "https://www.aoshearman.com",
        country: "UK",
        tags: ["law", "global"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.johnsonBanks,
      BRAND_REFS.spin,
      BRAND_REFS.ordinary,
      BRAND_REFS.bibliotheque,
    ],
  },
  logistics: {
    direct: [
      {
        name: "DHL",
        website: "https://www.dhl.com",
        country: "Germany",
        tags: ["logistics", "global"],
        bucket: "scale",
      },
      {
        name: "FedEx",
        website: "https://www.fedex.com",
        country: "USA",
        tags: ["logistics", "global"],
        bucket: "scale",
      },
      {
        name: "UPS",
        website: "https://www.ups.com",
        country: "USA",
        tags: ["logistics", "global"],
        bucket: "scale",
      },
      {
        name: "Flexport",
        website: "https://www.flexport.com",
        country: "USA",
        tags: ["freight", "digital"],
        bucket: "close",
      },
      {
        name: "ShipBob",
        website: "https://www.shipbob.com",
        country: "USA",
        tags: ["fulfillment", "ecommerce"],
        bucket: "close",
      },
      {
        name: "Maersk",
        website: "https://www.maersk.com",
        country: "Denmark",
        tags: ["shipping", "global"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.landor,
      BRAND_REFS.base,
      BRAND_REFS.instrument,
    ],
  },
  manufacturing: {
    direct: [
      {
        name: "Siemens",
        website: "https://www.siemens.com",
        country: "Germany",
        tags: ["industrial", "global"],
        bucket: "scale",
      },
      {
        name: "GE",
        website: "https://www.ge.com",
        country: "USA",
        tags: ["industrial", "global"],
        bucket: "scale",
      },
      {
        name: "3M",
        website: "https://www.3m.com",
        country: "USA",
        tags: ["materials", "innovation"],
        bucket: "adjacent",
      },
      {
        name: "Bosch",
        website: "https://www.bosch.com",
        country: "Germany",
        tags: ["engineering", "global"],
        bucket: "scale",
      },
      {
        name: "Haier",
        website: "https://www.haier.com",
        country: "China",
        tags: ["appliances", "global"],
        bucket: "regional",
      },
      {
        name: "Schneider Electric",
        website: "https://www.se.com",
        country: "France",
        tags: ["energy", "industrial"],
        bucket: "close",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.landor,
      BRAND_REFS.wolfOlins,
      BRAND_REFS.collins,
    ],
  },
  music: {
    direct: [
      {
        name: "Spotify",
        website: "https://www.spotify.com",
        country: "Sweden",
        tags: ["streaming", "platform"],
        bucket: "scale",
      },
      {
        name: "Apple Music",
        website: "https://www.apple.com/apple-music",
        country: "USA",
        tags: ["streaming", "platform"],
        bucket: "scale",
      },
      {
        name: "Universal Music Group",
        website: "https://www.universalmusic.com",
        country: "USA",
        tags: ["label", "global"],
        bucket: "scale",
      },
      {
        name: "Bandcamp",
        website: "https://bandcamp.com",
        country: "USA",
        tags: ["independent", "platform"],
        bucket: "close",
      },
      {
        name: "SoundCloud",
        website: "https://soundcloud.com",
        country: "Germany",
        tags: ["audio", "creators"],
        bucket: "close",
      },
      {
        name: "DistroKid",
        website: "https://distrokid.com",
        country: "USA",
        tags: ["distribution", "indie"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.franklyn,
      BRAND_REFS.dia,
      BRAND_REFS.mucho,
      BRAND_REFS.instrument,
    ],
  },
  pets: {
    direct: [
      {
        name: "Chewy",
        website: "https://www.chewy.com",
        country: "USA",
        tags: ["pets", "ecommerce"],
        bucket: "scale",
      },
      {
        name: "Petco",
        website: "https://www.petco.com",
        country: "USA",
        tags: ["pets", "retail"],
        bucket: "scale",
      },
      {
        name: "BarkBox",
        website: "https://www.barkbox.com",
        country: "USA",
        tags: ["pets", "subscription"],
        bucket: "close",
      },
      {
        name: "Rover",
        website: "https://www.rover.com",
        country: "USA",
        tags: ["pets", "services"],
        bucket: "close",
      },
      {
        name: "Zooplus",
        website: "https://www.zooplus.com",
        country: "Germany",
        tags: ["pets", "ecommerce"],
        bucket: "regional",
      },
      {
        name: "Ollie",
        website: "https://www.myollie.com",
        country: "USA",
        tags: ["pets", "food"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.mucho,
      BRAND_REFS.franklyn,
      BRAND_REFS.collins,
    ],
  },
  pharmaceuticals: {
    direct: [
      {
        name: "Pfizer",
        website: "https://www.pfizer.com",
        country: "USA",
        tags: ["pharma", "global"],
        bucket: "scale",
      },
      {
        name: "Novartis",
        website: "https://www.novartis.com",
        country: "Switzerland",
        tags: ["pharma", "global"],
        bucket: "scale",
      },
      {
        name: "Roche",
        website: "https://www.roche.com",
        country: "Switzerland",
        tags: ["pharma", "diagnostics"],
        bucket: "scale",
      },
      {
        name: "AstraZeneca",
        website: "https://www.astrazeneca.com",
        country: "UK",
        tags: ["pharma", "research"],
        bucket: "close",
      },
      {
        name: "Novo Nordisk",
        website: "https://www.novonordisk.com",
        country: "Denmark",
        tags: ["pharma", "metabolic"],
        bucket: "regional",
      },
      {
        name: "GSK",
        website: "https://www.gsk.com",
        country: "UK",
        tags: ["pharma", "global"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.landor,
      BRAND_REFS.collins,
      BRAND_REFS.wolfOlins,
    ],
  },
  "public-relations": {
    direct: [
      {
        name: "Edelman",
        website: "https://www.edelman.com",
        country: "USA",
        tags: ["pr", "global"],
        bucket: "scale",
      },
      {
        name: "Weber Shandwick",
        website: "https://www.webershandwick.com",
        country: "USA",
        tags: ["pr", "global"],
        bucket: "scale",
      },
      {
        name: "BCW",
        website: "https://www.bcw-global.com",
        country: "USA",
        tags: ["pr", "comms"],
        bucket: "scale",
      },
      {
        name: "FGS Global",
        website: "https://fgsglobal.com",
        country: "USA",
        tags: ["comms", "strategy"],
        bucket: "close",
      },
      {
        name: "Brunswick Group",
        website: "https://www.brunswickgroup.com",
        country: "UK",
        tags: ["comms", "advisory"],
        bucket: "close",
      },
      {
        name: "Hill+Knowlton",
        website: "https://www.hillandknowlton.com",
        country: "USA",
        tags: ["pr", "global"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.wolfOlins,
      BRAND_REFS.johnsonBanks,
      BRAND_REFS.franklyn,
    ],
  },
  publishing: {
    direct: [
      {
        name: "Penguin Random House",
        website: "https://www.penguinrandomhouse.com",
        country: "USA",
        tags: ["publishing", "global"],
        bucket: "scale",
      },
      {
        name: "HarperCollins",
        website: "https://www.harpercollins.com",
        country: "USA",
        tags: ["publishing", "global"],
        bucket: "scale",
      },
      {
        name: "The New York Times",
        website: "https://www.nytimes.com",
        country: "USA",
        tags: ["media", "editorial"],
        bucket: "adjacent",
      },
      {
        name: "Monocle",
        website: "https://monocle.com",
        country: "UK",
        tags: ["editorial", "culture"],
        bucket: "close",
      },
      {
        name: "Kinfolk",
        website: "https://www.kinfolk.com",
        country: "USA",
        tags: ["editorial", "lifestyle"],
        bucket: "close",
      },
      {
        name: "Phaidon",
        website: "https://www.phaidon.com",
        country: "UK",
        tags: ["art", "books"],
        bucket: "regional",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.ordinary,
      BRAND_REFS.spin,
      BRAND_REFS.bibliotheque,
      BRAND_REFS.jetset,
      BRAND_REFS.klim,
    ],
  },
  telecommunications: {
    direct: [
      {
        name: "Verizon",
        website: "https://www.verizon.com",
        country: "USA",
        tags: ["telecom", "scale"],
        bucket: "scale",
      },
      {
        name: "Deutsche Telekom",
        website: "https://www.telekom.com",
        country: "Germany",
        tags: ["telecom", "global"],
        bucket: "scale",
      },
      {
        name: "Vodafone",
        website: "https://www.vodafone.com",
        country: "UK",
        tags: ["telecom", "global"],
        bucket: "scale",
      },
      {
        name: "T-Mobile",
        website: "https://www.t-mobile.com",
        country: "USA",
        tags: ["telecom", "consumer"],
        bucket: "close",
      },
      {
        name: "Orange",
        website: "https://www.orange.com",
        country: "France",
        tags: ["telecom", "global"],
        bucket: "regional",
      },
      {
        name: "Twilio",
        website: "https://www.twilio.com",
        country: "USA",
        tags: ["comms", "api"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.landor,
      BRAND_REFS.wolfOlins,
      BRAND_REFS.instrument,
      BRAND_REFS.base,
    ],
  },
  "venture-capital": {
    direct: [
      {
        name: "a16z",
        website: "https://a16z.com",
        country: "USA",
        tags: ["vc", "tech"],
        bucket: "scale",
      },
      {
        name: "Sequoia Capital",
        website: "https://www.sequoiacap.com",
        country: "USA",
        tags: ["vc", "global"],
        bucket: "scale",
      },
      {
        name: "Accel",
        website: "https://www.accel.com",
        country: "USA",
        tags: ["vc", "growth"],
        bucket: "close",
      },
      {
        name: "Index Ventures",
        website: "https://www.indexventures.com",
        country: "UK",
        tags: ["vc", "europe"],
        bucket: "regional",
      },
      {
        name: "Benchmark",
        website: "https://www.benchmark.com",
        country: "USA",
        tags: ["vc", "early"],
        bucket: "close",
      },
      {
        name: "SoftBank Vision Fund",
        website: "https://visionfund.softbank.com",
        country: "Japan",
        tags: ["vc", "scale"],
        bucket: "adjacent",
      },
    ],
    references: [
      BRAND_REFS.pentagram,
      BRAND_REFS.collins,
      BRAND_REFS.order,
      BRAND_REFS.instrument,
      BRAND_REFS.franklyn,
    ],
  },
};

/** Extra company metadata for keyword-only names. */
export const COMPANY_CATALOG: Record<
  string,
  { website?: string; country?: string; tags?: string[]; reason?: string }
> = {
  "neri&hu": {
    website: "https://www.neriandhu.com",
    country: "China",
    tags: ["hospitality", "interior"],
  },
  "space copenhagen": {
    website: "https://spacecph.com",
    country: "Denmark",
    tags: ["hospitality", "interior"],
  },
  "yabu pushelberg": {
    website: "https://www.yabupushelberg.com",
    country: "Canada",
    tags: ["hospitality"],
  },
  "studio mumbai": {
    website: "https://www.studiomumbai.com",
    country: "India",
    tags: ["craft"],
  },
  "john pawson": {
    website: "https://www.johnpawson.com",
    country: "UK",
    tags: ["minimal", "residential"],
  },
  assemble: {
    website: "https://assemblestudio.co.uk",
    country: "UK",
    tags: ["cultural", "independent"],
  },
  "henning larsen": {
    website: "https://henninglarsen.com",
    country: "Denmark",
    tags: ["sustainable"],
  },
  "white arkitekter": {
    website: "https://whitearkitekter.com",
    country: "Sweden",
    tags: ["sustainable"],
  },
  lendager: {
    website: "https://lendager.com",
    country: "Denmark",
    tags: ["circular"],
  },
  "waugh thistleton architects": {
    website: "https://waughthistleton.com",
    country: "UK",
    tags: ["timber"],
  },
  openai: { website: "https://openai.com", country: "USA", tags: ["ai"] },
  anthropic: {
    website: "https://www.anthropic.com",
    country: "USA",
    tags: ["ai"],
  },
  perplexity: {
    website: "https://www.perplexity.ai",
    country: "USA",
    tags: ["ai"],
  },
  "hugging face": {
    website: "https://huggingface.co",
    country: "USA",
    tags: ["ai"],
  },
};
